-- Add EXPIRED status to events table
ALTER TABLE events MODIFY COLUMN status ENUM('OPEN', 'ACCEPTED', 'CONFIRMED', 'CANCELLED', 'RESERVATION_FAILED', 'COMPLETED', 'EXPIRED') NOT NULL DEFAULT 'OPEN';

