// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"strings"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
)

var defaultFaker = faker.New()

func random_CourtGroupsSurface(f *faker.Faker) CourtGroupsSurface {
	if f == nil {
		f = &defaultFaker
	}

	all := allCourtGroupsSurface()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_CourtGroupsType(f *faker.Faker) CourtGroupsType {
	if f == nil {
		f = &defaultFaker
	}

	all := allCourtGroupsType()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_EventsEventType(f *faker.Faker) EventsEventType {
	if f == nil {
		f = &defaultFaker
	}

	all := allEventsEventType()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_EventsSkillLevel(f *faker.Faker) EventsSkillLevel {
	if f == nil {
		f = &defaultFaker
	}

	all := allEventsSkillLevel()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_EventsStatus(f *faker.Faker) EventsStatus {
	if f == nil {
		f = &defaultFaker
	}

	all := allEventsStatus()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_JoinRequestsStatus(f *faker.Faker) JoinRequestsStatus {
	if f == nil {
		f = &defaultFaker
	}

	all := allJoinRequestsStatus()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_bool(f *faker.Faker) bool {
	if f == nil {
		f = &defaultFaker
	}

	return f.Bool()
}

func random_decimal_Decimal(f *faker.Faker) decimal.Decimal {
	if f == nil {
		f = &defaultFaker
	}

	return decimal.New(f.Int64Between(0, 1000), 0)
}

func random_int32(f *faker.Faker) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_int64(f *faker.Faker) int64 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int64()
}

func random_string(f *faker.Faker) string {
	if f == nil {
		f = &defaultFaker
	}

	return strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
}

func random_time_Time(f *faker.Faker) time.Time {
	if f == nil {
		f = &defaultFaker
	}

	year := time.Hour * 24 * 365
	min := time.Now().Add(-year)
	max := time.Now().Add(year)
	return f.Time().TimeBetween(min, max)
}
