// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

type Factory struct {
	baseConfirmationJoinRequestMods ConfirmationJoinRequestModSlice
	baseConfirmationMods            ConfirmationModSlice
	baseCourtGroupMods              CourtGroupModSlice
	baseEventLocationMods           EventLocationModSlice
	baseEventTimeSlotMods           EventTimeSlotModSlice
	baseEventMods                   EventModSlice
	baseFacilityMods                FacilityModSlice
	baseFacilityPartnerCardMods     FacilityPartnerCardModSlice
	baseJoinRequestLocationMods     JoinRequestLocationModSlice
	baseJoinRequestTimeSlotMods     JoinRequestTimeSlotModSlice
	baseJoinRequestMods             JoinRequestModSlice
	basePartnerCardMods             PartnerCardModSlice
	basePricePeriodMods             PricePeriodModSlice
	basePriceRuleMods               PriceRuleModSlice
	baseSchemaMigrationMods         SchemaMigrationModSlice
	baseUserPrefMods                UserPrefModSlice
	baseUserMods                    UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewConfirmationJoinRequest(mods ...ConfirmationJoinRequestMod) *ConfirmationJoinRequestTemplate {
	o := &ConfirmationJoinRequestTemplate{f: f}

	if f != nil {
		f.baseConfirmationJoinRequestMods.Apply(o)
	}

	ConfirmationJoinRequestModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewConfirmation(mods ...ConfirmationMod) *ConfirmationTemplate {
	o := &ConfirmationTemplate{f: f}

	if f != nil {
		f.baseConfirmationMods.Apply(o)
	}

	ConfirmationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewCourtGroup(mods ...CourtGroupMod) *CourtGroupTemplate {
	o := &CourtGroupTemplate{f: f}

	if f != nil {
		f.baseCourtGroupMods.Apply(o)
	}

	CourtGroupModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewEventLocation(mods ...EventLocationMod) *EventLocationTemplate {
	o := &EventLocationTemplate{f: f}

	if f != nil {
		f.baseEventLocationMods.Apply(o)
	}

	EventLocationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewEventTimeSlot(mods ...EventTimeSlotMod) *EventTimeSlotTemplate {
	o := &EventTimeSlotTemplate{f: f}

	if f != nil {
		f.baseEventTimeSlotMods.Apply(o)
	}

	EventTimeSlotModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewEvent(mods ...EventMod) *EventTemplate {
	o := &EventTemplate{f: f}

	if f != nil {
		f.baseEventMods.Apply(o)
	}

	EventModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewFacility(mods ...FacilityMod) *FacilityTemplate {
	o := &FacilityTemplate{f: f}

	if f != nil {
		f.baseFacilityMods.Apply(o)
	}

	FacilityModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewFacilityPartnerCard(mods ...FacilityPartnerCardMod) *FacilityPartnerCardTemplate {
	o := &FacilityPartnerCardTemplate{f: f}

	if f != nil {
		f.baseFacilityPartnerCardMods.Apply(o)
	}

	FacilityPartnerCardModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewJoinRequestLocation(mods ...JoinRequestLocationMod) *JoinRequestLocationTemplate {
	o := &JoinRequestLocationTemplate{f: f}

	if f != nil {
		f.baseJoinRequestLocationMods.Apply(o)
	}

	JoinRequestLocationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewJoinRequestTimeSlot(mods ...JoinRequestTimeSlotMod) *JoinRequestTimeSlotTemplate {
	o := &JoinRequestTimeSlotTemplate{f: f}

	if f != nil {
		f.baseJoinRequestTimeSlotMods.Apply(o)
	}

	JoinRequestTimeSlotModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewJoinRequest(mods ...JoinRequestMod) *JoinRequestTemplate {
	o := &JoinRequestTemplate{f: f}

	if f != nil {
		f.baseJoinRequestMods.Apply(o)
	}

	JoinRequestModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewPartnerCard(mods ...PartnerCardMod) *PartnerCardTemplate {
	o := &PartnerCardTemplate{f: f}

	if f != nil {
		f.basePartnerCardMods.Apply(o)
	}

	PartnerCardModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewPricePeriod(mods ...PricePeriodMod) *PricePeriodTemplate {
	o := &PricePeriodTemplate{f: f}

	if f != nil {
		f.basePricePeriodMods.Apply(o)
	}

	PricePeriodModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewPriceRule(mods ...PriceRuleMod) *PriceRuleTemplate {
	o := &PriceRuleTemplate{f: f}

	if f != nil {
		f.basePriceRuleMods.Apply(o)
	}

	PriceRuleModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewSchemaMigration(mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(o)
	}

	SchemaMigrationModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewUserPref(mods ...UserPrefMod) *UserPrefTemplate {
	o := &UserPrefTemplate{f: f}

	if f != nil {
		f.baseUserPrefMods.Apply(o)
	}

	UserPrefModSlice(mods).Apply(o)

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(o)
	}

	UserModSlice(mods).Apply(o)

	return o
}

func (f *Factory) ClearBaseConfirmationJoinRequestMods() {
	f.baseConfirmationJoinRequestMods = nil
}

func (f *Factory) AddBaseConfirmationJoinRequestMod(mods ...ConfirmationJoinRequestMod) {
	f.baseConfirmationJoinRequestMods = append(f.baseConfirmationJoinRequestMods, mods...)
}

func (f *Factory) ClearBaseConfirmationMods() {
	f.baseConfirmationMods = nil
}

func (f *Factory) AddBaseConfirmationMod(mods ...ConfirmationMod) {
	f.baseConfirmationMods = append(f.baseConfirmationMods, mods...)
}

func (f *Factory) ClearBaseCourtGroupMods() {
	f.baseCourtGroupMods = nil
}

func (f *Factory) AddBaseCourtGroupMod(mods ...CourtGroupMod) {
	f.baseCourtGroupMods = append(f.baseCourtGroupMods, mods...)
}

func (f *Factory) ClearBaseEventLocationMods() {
	f.baseEventLocationMods = nil
}

func (f *Factory) AddBaseEventLocationMod(mods ...EventLocationMod) {
	f.baseEventLocationMods = append(f.baseEventLocationMods, mods...)
}

func (f *Factory) ClearBaseEventTimeSlotMods() {
	f.baseEventTimeSlotMods = nil
}

func (f *Factory) AddBaseEventTimeSlotMod(mods ...EventTimeSlotMod) {
	f.baseEventTimeSlotMods = append(f.baseEventTimeSlotMods, mods...)
}

func (f *Factory) ClearBaseEventMods() {
	f.baseEventMods = nil
}

func (f *Factory) AddBaseEventMod(mods ...EventMod) {
	f.baseEventMods = append(f.baseEventMods, mods...)
}

func (f *Factory) ClearBaseFacilityMods() {
	f.baseFacilityMods = nil
}

func (f *Factory) AddBaseFacilityMod(mods ...FacilityMod) {
	f.baseFacilityMods = append(f.baseFacilityMods, mods...)
}

func (f *Factory) ClearBaseFacilityPartnerCardMods() {
	f.baseFacilityPartnerCardMods = nil
}

func (f *Factory) AddBaseFacilityPartnerCardMod(mods ...FacilityPartnerCardMod) {
	f.baseFacilityPartnerCardMods = append(f.baseFacilityPartnerCardMods, mods...)
}

func (f *Factory) ClearBaseJoinRequestLocationMods() {
	f.baseJoinRequestLocationMods = nil
}

func (f *Factory) AddBaseJoinRequestLocationMod(mods ...JoinRequestLocationMod) {
	f.baseJoinRequestLocationMods = append(f.baseJoinRequestLocationMods, mods...)
}

func (f *Factory) ClearBaseJoinRequestTimeSlotMods() {
	f.baseJoinRequestTimeSlotMods = nil
}

func (f *Factory) AddBaseJoinRequestTimeSlotMod(mods ...JoinRequestTimeSlotMod) {
	f.baseJoinRequestTimeSlotMods = append(f.baseJoinRequestTimeSlotMods, mods...)
}

func (f *Factory) ClearBaseJoinRequestMods() {
	f.baseJoinRequestMods = nil
}

func (f *Factory) AddBaseJoinRequestMod(mods ...JoinRequestMod) {
	f.baseJoinRequestMods = append(f.baseJoinRequestMods, mods...)
}

func (f *Factory) ClearBasePartnerCardMods() {
	f.basePartnerCardMods = nil
}

func (f *Factory) AddBasePartnerCardMod(mods ...PartnerCardMod) {
	f.basePartnerCardMods = append(f.basePartnerCardMods, mods...)
}

func (f *Factory) ClearBasePricePeriodMods() {
	f.basePricePeriodMods = nil
}

func (f *Factory) AddBasePricePeriodMod(mods ...PricePeriodMod) {
	f.basePricePeriodMods = append(f.basePricePeriodMods, mods...)
}

func (f *Factory) ClearBasePriceRuleMods() {
	f.basePriceRuleMods = nil
}

func (f *Factory) AddBasePriceRuleMod(mods ...PriceRuleMod) {
	f.basePriceRuleMods = append(f.basePriceRuleMods, mods...)
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}

func (f *Factory) ClearBaseUserPrefMods() {
	f.baseUserPrefMods = nil
}

func (f *Factory) AddBaseUserPrefMod(mods ...UserPrefMod) {
	f.baseUserPrefMods = append(f.baseUserPrefMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
