// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type contextKey string

var (
	confirmationJoinRequestCtx = newContextual[*models.ConfirmationJoinRequest]("confirmationJoinRequest")
	confirmationCtx            = newContextual[*models.Confirmation]("confirmation")
	courtGroupCtx              = newContextual[*models.CourtGroup]("courtGroup")
	eventLocationCtx           = newContextual[*models.EventLocation]("eventLocation")
	eventTimeSlotCtx           = newContextual[*models.EventTimeSlot]("eventTimeSlot")
	eventCtx                   = newContextual[*models.Event]("event")
	facilityCtx                = newContextual[*models.Facility]("facility")
	facilityPartnerCardCtx     = newContextual[*models.FacilityPartnerCard]("facilityPartnerCard")
	joinRequestLocationCtx     = newContextual[*models.JoinRequestLocation]("joinRequestLocation")
	joinRequestTimeSlotCtx     = newContextual[*models.JoinRequestTimeSlot]("joinRequestTimeSlot")
	joinRequestCtx             = newContextual[*models.JoinRequest]("joinRequest")
	partnerCardCtx             = newContextual[*models.PartnerCard]("partnerCard")
	pricePeriodCtx             = newContextual[*models.PricePeriod]("pricePeriod")
	priceRuleCtx               = newContextual[*models.PriceRule]("priceRule")
	schemaMigrationCtx         = newContextual[*models.SchemaMigration]("schemaMigration")
	userPrefCtx                = newContextual[*models.UserPref]("userPref")
	userCtx                    = newContextual[*models.User]("user")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
