// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type ConfirmationJoinRequestMod interface {
	Apply(*ConfirmationJoinRequestTemplate)
}

type ConfirmationJoinRequestModFunc func(*ConfirmationJoinRequestTemplate)

func (f ConfirmationJoinRequestModFunc) Apply(n *ConfirmationJoinRequestTemplate) {
	f(n)
}

type ConfirmationJoinRequestModSlice []ConfirmationJoinRequestMod

func (mods ConfirmationJoinRequestModSlice) Apply(n *ConfirmationJoinRequestTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// ConfirmationJoinRequestTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConfirmationJoinRequestTemplate struct {
	ConfirmationID func() string
	JoinRequestID  func() string

	r confirmationJoinRequestR
	f *Factory
}

type confirmationJoinRequestR struct {
	Confirmation *confirmationJoinRequestRConfirmationR
	JoinRequest  *confirmationJoinRequestRJoinRequestR
}

type confirmationJoinRequestRConfirmationR struct {
	o *ConfirmationTemplate
}
type confirmationJoinRequestRJoinRequestR struct {
	o *JoinRequestTemplate
}

// Apply mods to the ConfirmationJoinRequestTemplate
func (o *ConfirmationJoinRequestTemplate) Apply(mods ...ConfirmationJoinRequestMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.ConfirmationJoinRequest
// this does nothing with the relationship templates
func (o ConfirmationJoinRequestTemplate) toModel() *models.ConfirmationJoinRequest {
	m := &models.ConfirmationJoinRequest{}

	if o.ConfirmationID != nil {
		m.ConfirmationID = o.ConfirmationID()
	}
	if o.JoinRequestID != nil {
		m.JoinRequestID = o.JoinRequestID()
	}

	return m
}

// toModels returns an models.ConfirmationJoinRequestSlice
// this does nothing with the relationship templates
func (o ConfirmationJoinRequestTemplate) toModels(number int) models.ConfirmationJoinRequestSlice {
	m := make(models.ConfirmationJoinRequestSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.ConfirmationJoinRequest
// according to the relationships in the template. Nothing is inserted into the db
func (t ConfirmationJoinRequestTemplate) setModelRels(o *models.ConfirmationJoinRequest) {
	if t.r.Confirmation != nil {
		rel := t.r.Confirmation.o.toModel()
		o.ConfirmationID = rel.ID
		o.R.Confirmation = rel
	}

	if t.r.JoinRequest != nil {
		rel := t.r.JoinRequest.o.toModel()
		o.JoinRequestID = rel.ID
		o.R.JoinRequest = rel
	}
}

// BuildSetter returns an *models.ConfirmationJoinRequestSetter
// this does nothing with the relationship templates
func (o ConfirmationJoinRequestTemplate) BuildSetter() *models.ConfirmationJoinRequestSetter {
	m := &models.ConfirmationJoinRequestSetter{}

	if o.ConfirmationID != nil {
		m.ConfirmationID = omit.From(o.ConfirmationID())
	}
	if o.JoinRequestID != nil {
		m.JoinRequestID = omit.From(o.JoinRequestID())
	}

	return m
}

// BuildManySetter returns an []*models.ConfirmationJoinRequestSetter
// this does nothing with the relationship templates
func (o ConfirmationJoinRequestTemplate) BuildManySetter(number int) []*models.ConfirmationJoinRequestSetter {
	m := make([]*models.ConfirmationJoinRequestSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ConfirmationJoinRequest
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConfirmationJoinRequestTemplate.Create
func (o ConfirmationJoinRequestTemplate) Build() *models.ConfirmationJoinRequest {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConfirmationJoinRequestSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConfirmationJoinRequestTemplate.CreateMany
func (o ConfirmationJoinRequestTemplate) BuildMany(number int) models.ConfirmationJoinRequestSlice {
	m := make(models.ConfirmationJoinRequestSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConfirmationJoinRequest(m *models.ConfirmationJoinRequestSetter) {
	if m.ConfirmationID.IsUnset() {
		m.ConfirmationID = omit.From(random_string(nil))
	}
	if m.JoinRequestID.IsUnset() {
		m.JoinRequestID = omit.From(random_string(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ConfirmationJoinRequest
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConfirmationJoinRequestTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ConfirmationJoinRequest) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a confirmationJoinRequest and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConfirmationJoinRequestTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ConfirmationJoinRequest, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a confirmationJoinRequest and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConfirmationJoinRequestTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ConfirmationJoinRequest {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a confirmationJoinRequest and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConfirmationJoinRequestTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ConfirmationJoinRequest {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a confirmationJoinRequest and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *ConfirmationJoinRequestTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.ConfirmationJoinRequest, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConfirmationJoinRequest(opt)

	var rel0 *models.Confirmation
	if o.r.Confirmation == nil {
		var ok bool
		rel0, ok = confirmationCtx.Value(ctx)
		if !ok {
			ConfirmationJoinRequestMods.WithNewConfirmation().Apply(o)
		}
	}
	if o.r.Confirmation != nil {
		ctx, rel0, err = o.r.Confirmation.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.ConfirmationID = omit.From(rel0.ID)

	var rel1 *models.JoinRequest
	if o.r.JoinRequest == nil {
		var ok bool
		rel1, ok = joinRequestCtx.Value(ctx)
		if !ok {
			ConfirmationJoinRequestMods.WithNewJoinRequest().Apply(o)
		}
	}
	if o.r.JoinRequest != nil {
		ctx, rel1, err = o.r.JoinRequest.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.JoinRequestID = omit.From(rel1.ID)

	m, err := models.ConfirmationJoinRequests.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = confirmationJoinRequestCtx.WithValue(ctx, m)

	m.R.Confirmation = rel0
	m.R.JoinRequest = rel1

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple confirmationJoinRequests and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConfirmationJoinRequestTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConfirmationJoinRequestSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple confirmationJoinRequests and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConfirmationJoinRequestTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConfirmationJoinRequestSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple confirmationJoinRequests and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConfirmationJoinRequestTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConfirmationJoinRequestSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple confirmationJoinRequests and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o ConfirmationJoinRequestTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.ConfirmationJoinRequestSlice, error) {
	var err error
	m := make(models.ConfirmationJoinRequestSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// ConfirmationJoinRequest has methods that act as mods for the ConfirmationJoinRequestTemplate
var ConfirmationJoinRequestMods confirmationJoinRequestMods

type confirmationJoinRequestMods struct{}

func (m confirmationJoinRequestMods) RandomizeAllColumns(f *faker.Faker) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModSlice{
		ConfirmationJoinRequestMods.RandomConfirmationID(f),
		ConfirmationJoinRequestMods.RandomJoinRequestID(f),
	}
}

// Set the model columns to this value
func (m confirmationJoinRequestMods) ConfirmationID(val string) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.ConfirmationID = func() string { return val }
	})
}

// Set the Column from the function
func (m confirmationJoinRequestMods) ConfirmationIDFunc(f func() string) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.ConfirmationID = f
	})
}

// Clear any values for the column
func (m confirmationJoinRequestMods) UnsetConfirmationID() ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.ConfirmationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m confirmationJoinRequestMods) RandomConfirmationID(f *faker.Faker) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.ConfirmationID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m confirmationJoinRequestMods) JoinRequestID(val string) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.JoinRequestID = func() string { return val }
	})
}

// Set the Column from the function
func (m confirmationJoinRequestMods) JoinRequestIDFunc(f func() string) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.JoinRequestID = f
	})
}

// Clear any values for the column
func (m confirmationJoinRequestMods) UnsetJoinRequestID() ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.JoinRequestID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m confirmationJoinRequestMods) RandomJoinRequestID(f *faker.Faker) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.JoinRequestID = func() string {
			return random_string(f)
		}
	})
}

func (m confirmationJoinRequestMods) WithConfirmation(rel *ConfirmationTemplate) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.r.Confirmation = &confirmationJoinRequestRConfirmationR{
			o: rel,
		}
	})
}

func (m confirmationJoinRequestMods) WithNewConfirmation(mods ...ConfirmationMod) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		related := o.f.NewConfirmation(mods...)

		m.WithConfirmation(related).Apply(o)
	})
}

func (m confirmationJoinRequestMods) WithoutConfirmation() ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.r.Confirmation = nil
	})
}

func (m confirmationJoinRequestMods) WithJoinRequest(rel *JoinRequestTemplate) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.r.JoinRequest = &confirmationJoinRequestRJoinRequestR{
			o: rel,
		}
	})
}

func (m confirmationJoinRequestMods) WithNewJoinRequest(mods ...JoinRequestMod) ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		related := o.f.NewJoinRequest(mods...)

		m.WithJoinRequest(related).Apply(o)
	})
}

func (m confirmationJoinRequestMods) WithoutJoinRequest() ConfirmationJoinRequestMod {
	return ConfirmationJoinRequestModFunc(func(o *ConfirmationJoinRequestTemplate) {
		o.r.JoinRequest = nil
	})
}
