// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type EventTimeSlotMod interface {
	Apply(*EventTimeSlotTemplate)
}

type EventTimeSlotModFunc func(*EventTimeSlotTemplate)

func (f EventTimeSlotModFunc) Apply(n *EventTimeSlotTemplate) {
	f(n)
}

type EventTimeSlotModSlice []EventTimeSlotMod

func (mods EventTimeSlotModSlice) Apply(n *EventTimeSlotTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// EventTimeSlotTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type EventTimeSlotTemplate struct {
	ID      func() string
	EventID func() string
	Date    func() time.Time
	Time    func() int32

	r eventTimeSlotR
	f *Factory
}

type eventTimeSlotR struct {
	Event *eventTimeSlotREventR
}

type eventTimeSlotREventR struct {
	o *EventTemplate
}

// Apply mods to the EventTimeSlotTemplate
func (o *EventTimeSlotTemplate) Apply(mods ...EventTimeSlotMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.EventTimeSlot
// this does nothing with the relationship templates
func (o EventTimeSlotTemplate) toModel() *models.EventTimeSlot {
	m := &models.EventTimeSlot{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.EventID != nil {
		m.EventID = o.EventID()
	}
	if o.Date != nil {
		m.Date = o.Date()
	}
	if o.Time != nil {
		m.Time = o.Time()
	}

	return m
}

// toModels returns an models.EventTimeSlotSlice
// this does nothing with the relationship templates
func (o EventTimeSlotTemplate) toModels(number int) models.EventTimeSlotSlice {
	m := make(models.EventTimeSlotSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.EventTimeSlot
// according to the relationships in the template. Nothing is inserted into the db
func (t EventTimeSlotTemplate) setModelRels(o *models.EventTimeSlot) {
	if t.r.Event != nil {
		rel := t.r.Event.o.toModel()
		rel.R.EventTimeSlots = append(rel.R.EventTimeSlots, o)
		o.EventID = rel.ID
		o.R.Event = rel
	}
}

// BuildSetter returns an *models.EventTimeSlotSetter
// this does nothing with the relationship templates
func (o EventTimeSlotTemplate) BuildSetter() *models.EventTimeSlotSetter {
	m := &models.EventTimeSlotSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.EventID != nil {
		m.EventID = omit.From(o.EventID())
	}
	if o.Date != nil {
		m.Date = omit.From(o.Date())
	}
	if o.Time != nil {
		m.Time = omit.From(o.Time())
	}

	return m
}

// BuildManySetter returns an []*models.EventTimeSlotSetter
// this does nothing with the relationship templates
func (o EventTimeSlotTemplate) BuildManySetter(number int) []*models.EventTimeSlotSetter {
	m := make([]*models.EventTimeSlotSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.EventTimeSlot
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EventTimeSlotTemplate.Create
func (o EventTimeSlotTemplate) Build() *models.EventTimeSlot {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.EventTimeSlotSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EventTimeSlotTemplate.CreateMany
func (o EventTimeSlotTemplate) BuildMany(number int) models.EventTimeSlotSlice {
	m := make(models.EventTimeSlotSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableEventTimeSlot(m *models.EventTimeSlotSetter) {
	if m.ID.IsUnset() {
		m.ID = omit.From(random_string(nil))
	}
	if m.EventID.IsUnset() {
		m.EventID = omit.From(random_string(nil))
	}
	if m.Date.IsUnset() {
		m.Date = omit.From(random_time_Time(nil))
	}
	if m.Time.IsUnset() {
		m.Time = omit.From(random_int32(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.EventTimeSlot
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *EventTimeSlotTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.EventTimeSlot) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a eventTimeSlot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *EventTimeSlotTemplate) Create(ctx context.Context, exec bob.Executor) (*models.EventTimeSlot, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a eventTimeSlot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *EventTimeSlotTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.EventTimeSlot {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a eventTimeSlot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *EventTimeSlotTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.EventTimeSlot {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a eventTimeSlot and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *EventTimeSlotTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.EventTimeSlot, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableEventTimeSlot(opt)

	var rel0 *models.Event
	if o.r.Event == nil {
		var ok bool
		rel0, ok = eventCtx.Value(ctx)
		if !ok {
			EventTimeSlotMods.WithNewEvent().Apply(o)
		}
	}
	if o.r.Event != nil {
		ctx, rel0, err = o.r.Event.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.EventID = omit.From(rel0.ID)

	m, err := models.EventTimeSlots.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = eventTimeSlotCtx.WithValue(ctx, m)

	m.R.Event = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple eventTimeSlots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o EventTimeSlotTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.EventTimeSlotSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple eventTimeSlots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o EventTimeSlotTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.EventTimeSlotSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple eventTimeSlots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o EventTimeSlotTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.EventTimeSlotSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple eventTimeSlots and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o EventTimeSlotTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.EventTimeSlotSlice, error) {
	var err error
	m := make(models.EventTimeSlotSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// EventTimeSlot has methods that act as mods for the EventTimeSlotTemplate
var EventTimeSlotMods eventTimeSlotMods

type eventTimeSlotMods struct{}

func (m eventTimeSlotMods) RandomizeAllColumns(f *faker.Faker) EventTimeSlotMod {
	return EventTimeSlotModSlice{
		EventTimeSlotMods.RandomID(f),
		EventTimeSlotMods.RandomEventID(f),
		EventTimeSlotMods.RandomDate(f),
		EventTimeSlotMods.RandomTime(f),
	}
}

// Set the model columns to this value
func (m eventTimeSlotMods) ID(val string) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m eventTimeSlotMods) IDFunc(f func() string) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m eventTimeSlotMods) UnsetID() EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m eventTimeSlotMods) RandomID(f *faker.Faker) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m eventTimeSlotMods) EventID(val string) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.EventID = func() string { return val }
	})
}

// Set the Column from the function
func (m eventTimeSlotMods) EventIDFunc(f func() string) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.EventID = f
	})
}

// Clear any values for the column
func (m eventTimeSlotMods) UnsetEventID() EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.EventID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m eventTimeSlotMods) RandomEventID(f *faker.Faker) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.EventID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m eventTimeSlotMods) Date(val time.Time) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Date = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m eventTimeSlotMods) DateFunc(f func() time.Time) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Date = f
	})
}

// Clear any values for the column
func (m eventTimeSlotMods) UnsetDate() EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Date = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m eventTimeSlotMods) RandomDate(f *faker.Faker) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Date = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m eventTimeSlotMods) Time(val int32) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Time = func() int32 { return val }
	})
}

// Set the Column from the function
func (m eventTimeSlotMods) TimeFunc(f func() int32) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Time = f
	})
}

// Clear any values for the column
func (m eventTimeSlotMods) UnsetTime() EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Time = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m eventTimeSlotMods) RandomTime(f *faker.Faker) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.Time = func() int32 {
			return random_int32(f)
		}
	})
}

func (m eventTimeSlotMods) WithEvent(rel *EventTemplate) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.r.Event = &eventTimeSlotREventR{
			o: rel,
		}
	})
}

func (m eventTimeSlotMods) WithNewEvent(mods ...EventMod) EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		related := o.f.NewEvent(mods...)

		m.WithEvent(related).Apply(o)
	})
}

func (m eventTimeSlotMods) WithoutEvent() EventTimeSlotMod {
	return EventTimeSlotModFunc(func(o *EventTimeSlotTemplate) {
		o.r.Event = nil
	})
}
