// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type JoinRequestLocationMod interface {
	Apply(*JoinRequestLocationTemplate)
}

type JoinRequestLocationModFunc func(*JoinRequestLocationTemplate)

func (f JoinRequestLocationModFunc) Apply(n *JoinRequestLocationTemplate) {
	f(n)
}

type JoinRequestLocationModSlice []JoinRequestLocationMod

func (mods JoinRequestLocationModSlice) Apply(n *JoinRequestLocationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// JoinRequestLocationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type JoinRequestLocationTemplate struct {
	JoinRequestID func() string
	LocationID    func() string

	r joinRequestLocationR
	f *Factory
}

type joinRequestLocationR struct {
	JoinRequest      *joinRequestLocationRJoinRequestR
	LocationFacility *joinRequestLocationRLocationFacilityR
}

type joinRequestLocationRJoinRequestR struct {
	o *JoinRequestTemplate
}
type joinRequestLocationRLocationFacilityR struct {
	o *FacilityTemplate
}

// Apply mods to the JoinRequestLocationTemplate
func (o *JoinRequestLocationTemplate) Apply(mods ...JoinRequestLocationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.JoinRequestLocation
// this does nothing with the relationship templates
func (o JoinRequestLocationTemplate) toModel() *models.JoinRequestLocation {
	m := &models.JoinRequestLocation{}

	if o.JoinRequestID != nil {
		m.JoinRequestID = o.JoinRequestID()
	}
	if o.LocationID != nil {
		m.LocationID = o.LocationID()
	}

	return m
}

// toModels returns an models.JoinRequestLocationSlice
// this does nothing with the relationship templates
func (o JoinRequestLocationTemplate) toModels(number int) models.JoinRequestLocationSlice {
	m := make(models.JoinRequestLocationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.JoinRequestLocation
// according to the relationships in the template. Nothing is inserted into the db
func (t JoinRequestLocationTemplate) setModelRels(o *models.JoinRequestLocation) {
	if t.r.JoinRequest != nil {
		rel := t.r.JoinRequest.o.toModel()
		o.JoinRequestID = rel.ID
		o.R.JoinRequest = rel
	}

	if t.r.LocationFacility != nil {
		rel := t.r.LocationFacility.o.toModel()
		o.LocationID = rel.ID
		o.R.LocationFacility = rel
	}
}

// BuildSetter returns an *models.JoinRequestLocationSetter
// this does nothing with the relationship templates
func (o JoinRequestLocationTemplate) BuildSetter() *models.JoinRequestLocationSetter {
	m := &models.JoinRequestLocationSetter{}

	if o.JoinRequestID != nil {
		m.JoinRequestID = omit.From(o.JoinRequestID())
	}
	if o.LocationID != nil {
		m.LocationID = omit.From(o.LocationID())
	}

	return m
}

// BuildManySetter returns an []*models.JoinRequestLocationSetter
// this does nothing with the relationship templates
func (o JoinRequestLocationTemplate) BuildManySetter(number int) []*models.JoinRequestLocationSetter {
	m := make([]*models.JoinRequestLocationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.JoinRequestLocation
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use JoinRequestLocationTemplate.Create
func (o JoinRequestLocationTemplate) Build() *models.JoinRequestLocation {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.JoinRequestLocationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use JoinRequestLocationTemplate.CreateMany
func (o JoinRequestLocationTemplate) BuildMany(number int) models.JoinRequestLocationSlice {
	m := make(models.JoinRequestLocationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableJoinRequestLocation(m *models.JoinRequestLocationSetter) {
	if m.JoinRequestID.IsUnset() {
		m.JoinRequestID = omit.From(random_string(nil))
	}
	if m.LocationID.IsUnset() {
		m.LocationID = omit.From(random_string(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.JoinRequestLocation
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *JoinRequestLocationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.JoinRequestLocation) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a joinRequestLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *JoinRequestLocationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.JoinRequestLocation, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a joinRequestLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *JoinRequestLocationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.JoinRequestLocation {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a joinRequestLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *JoinRequestLocationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.JoinRequestLocation {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a joinRequestLocation and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *JoinRequestLocationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.JoinRequestLocation, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableJoinRequestLocation(opt)

	var rel0 *models.JoinRequest
	if o.r.JoinRequest == nil {
		var ok bool
		rel0, ok = joinRequestCtx.Value(ctx)
		if !ok {
			JoinRequestLocationMods.WithNewJoinRequest().Apply(o)
		}
	}
	if o.r.JoinRequest != nil {
		ctx, rel0, err = o.r.JoinRequest.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.JoinRequestID = omit.From(rel0.ID)

	var rel1 *models.Facility
	if o.r.LocationFacility == nil {
		var ok bool
		rel1, ok = facilityCtx.Value(ctx)
		if !ok {
			JoinRequestLocationMods.WithNewLocationFacility().Apply(o)
		}
	}
	if o.r.LocationFacility != nil {
		ctx, rel1, err = o.r.LocationFacility.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.LocationID = omit.From(rel1.ID)

	m, err := models.JoinRequestLocations.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = joinRequestLocationCtx.WithValue(ctx, m)

	m.R.JoinRequest = rel0
	m.R.LocationFacility = rel1

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple joinRequestLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o JoinRequestLocationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.JoinRequestLocationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple joinRequestLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o JoinRequestLocationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.JoinRequestLocationSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple joinRequestLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o JoinRequestLocationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.JoinRequestLocationSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple joinRequestLocations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o JoinRequestLocationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.JoinRequestLocationSlice, error) {
	var err error
	m := make(models.JoinRequestLocationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// JoinRequestLocation has methods that act as mods for the JoinRequestLocationTemplate
var JoinRequestLocationMods joinRequestLocationMods

type joinRequestLocationMods struct{}

func (m joinRequestLocationMods) RandomizeAllColumns(f *faker.Faker) JoinRequestLocationMod {
	return JoinRequestLocationModSlice{
		JoinRequestLocationMods.RandomJoinRequestID(f),
		JoinRequestLocationMods.RandomLocationID(f),
	}
}

// Set the model columns to this value
func (m joinRequestLocationMods) JoinRequestID(val string) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.JoinRequestID = func() string { return val }
	})
}

// Set the Column from the function
func (m joinRequestLocationMods) JoinRequestIDFunc(f func() string) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.JoinRequestID = f
	})
}

// Clear any values for the column
func (m joinRequestLocationMods) UnsetJoinRequestID() JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.JoinRequestID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m joinRequestLocationMods) RandomJoinRequestID(f *faker.Faker) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.JoinRequestID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m joinRequestLocationMods) LocationID(val string) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.LocationID = func() string { return val }
	})
}

// Set the Column from the function
func (m joinRequestLocationMods) LocationIDFunc(f func() string) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.LocationID = f
	})
}

// Clear any values for the column
func (m joinRequestLocationMods) UnsetLocationID() JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.LocationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m joinRequestLocationMods) RandomLocationID(f *faker.Faker) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.LocationID = func() string {
			return random_string(f)
		}
	})
}

func (m joinRequestLocationMods) WithJoinRequest(rel *JoinRequestTemplate) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.r.JoinRequest = &joinRequestLocationRJoinRequestR{
			o: rel,
		}
	})
}

func (m joinRequestLocationMods) WithNewJoinRequest(mods ...JoinRequestMod) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		related := o.f.NewJoinRequest(mods...)

		m.WithJoinRequest(related).Apply(o)
	})
}

func (m joinRequestLocationMods) WithoutJoinRequest() JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.r.JoinRequest = nil
	})
}

func (m joinRequestLocationMods) WithLocationFacility(rel *FacilityTemplate) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.r.LocationFacility = &joinRequestLocationRLocationFacilityR{
			o: rel,
		}
	})
}

func (m joinRequestLocationMods) WithNewLocationFacility(mods ...FacilityMod) JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		related := o.f.NewFacility(mods...)

		m.WithLocationFacility(related).Apply(o)
	})
}

func (m joinRequestLocationMods) WithoutLocationFacility() JoinRequestLocationMod {
	return JoinRequestLocationModFunc(func(o *JoinRequestLocationTemplate) {
		o.r.LocationFacility = nil
	})
}
