// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type PriceRuleMod interface {
	Apply(*PriceRuleTemplate)
}

type PriceRuleModFunc func(*PriceRuleTemplate)

func (f PriceRuleModFunc) Apply(n *PriceRuleTemplate) {
	f(n)
}

type PriceRuleModSlice []PriceRuleMod

func (mods PriceRuleModSlice) Apply(n *PriceRuleTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// PriceRuleTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type PriceRuleTemplate struct {
	ID            func() int32
	PricePeriodID func() int32
	DayPattern    func() string
	TimeStart     func() string
	TimeEnd       func() string
	Price         func() decimal.Decimal

	r priceRuleR
	f *Factory
}

type priceRuleR struct {
	PricePeriod *priceRuleRPricePeriodR
}

type priceRuleRPricePeriodR struct {
	o *PricePeriodTemplate
}

// Apply mods to the PriceRuleTemplate
func (o *PriceRuleTemplate) Apply(mods ...PriceRuleMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.PriceRule
// this does nothing with the relationship templates
func (o PriceRuleTemplate) toModel() *models.PriceRule {
	m := &models.PriceRule{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.PricePeriodID != nil {
		m.PricePeriodID = o.PricePeriodID()
	}
	if o.DayPattern != nil {
		m.DayPattern = o.DayPattern()
	}
	if o.TimeStart != nil {
		m.TimeStart = o.TimeStart()
	}
	if o.TimeEnd != nil {
		m.TimeEnd = o.TimeEnd()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}

	return m
}

// toModels returns an models.PriceRuleSlice
// this does nothing with the relationship templates
func (o PriceRuleTemplate) toModels(number int) models.PriceRuleSlice {
	m := make(models.PriceRuleSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.PriceRule
// according to the relationships in the template. Nothing is inserted into the db
func (t PriceRuleTemplate) setModelRels(o *models.PriceRule) {
	if t.r.PricePeriod != nil {
		rel := t.r.PricePeriod.o.toModel()
		rel.R.PriceRules = append(rel.R.PriceRules, o)
		o.PricePeriodID = rel.ID
		o.R.PricePeriod = rel
	}
}

// BuildSetter returns an *models.PriceRuleSetter
// this does nothing with the relationship templates
func (o PriceRuleTemplate) BuildSetter() *models.PriceRuleSetter {
	m := &models.PriceRuleSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.PricePeriodID != nil {
		m.PricePeriodID = omit.From(o.PricePeriodID())
	}
	if o.DayPattern != nil {
		m.DayPattern = omit.From(o.DayPattern())
	}
	if o.TimeStart != nil {
		m.TimeStart = omit.From(o.TimeStart())
	}
	if o.TimeEnd != nil {
		m.TimeEnd = omit.From(o.TimeEnd())
	}
	if o.Price != nil {
		m.Price = omit.From(o.Price())
	}

	return m
}

// BuildManySetter returns an []*models.PriceRuleSetter
// this does nothing with the relationship templates
func (o PriceRuleTemplate) BuildManySetter(number int) []*models.PriceRuleSetter {
	m := make([]*models.PriceRuleSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.PriceRule
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PriceRuleTemplate.Create
func (o PriceRuleTemplate) Build() *models.PriceRule {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.PriceRuleSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PriceRuleTemplate.CreateMany
func (o PriceRuleTemplate) BuildMany(number int) models.PriceRuleSlice {
	m := make(models.PriceRuleSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatablePriceRule(m *models.PriceRuleSetter) {
	if m.PricePeriodID.IsUnset() {
		m.PricePeriodID = omit.From(random_int32(nil))
	}
	if m.DayPattern.IsUnset() {
		m.DayPattern = omit.From(random_string(nil))
	}
	if m.TimeStart.IsUnset() {
		m.TimeStart = omit.From(random_string(nil))
	}
	if m.TimeEnd.IsUnset() {
		m.TimeEnd = omit.From(random_string(nil))
	}
	if m.Price.IsUnset() {
		m.Price = omit.From(random_decimal_Decimal(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.PriceRule
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *PriceRuleTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.PriceRule) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a priceRule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *PriceRuleTemplate) Create(ctx context.Context, exec bob.Executor) (*models.PriceRule, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a priceRule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *PriceRuleTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.PriceRule {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a priceRule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *PriceRuleTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.PriceRule {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a priceRule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *PriceRuleTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.PriceRule, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatablePriceRule(opt)

	var rel0 *models.PricePeriod
	if o.r.PricePeriod == nil {
		var ok bool
		rel0, ok = pricePeriodCtx.Value(ctx)
		if !ok {
			PriceRuleMods.WithNewPricePeriod().Apply(o)
		}
	}
	if o.r.PricePeriod != nil {
		ctx, rel0, err = o.r.PricePeriod.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.PricePeriodID = omit.From(rel0.ID)

	m, err := models.PriceRules.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = priceRuleCtx.WithValue(ctx, m)

	m.R.PricePeriod = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple priceRules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o PriceRuleTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.PriceRuleSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple priceRules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o PriceRuleTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.PriceRuleSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple priceRules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o PriceRuleTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.PriceRuleSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple priceRules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o PriceRuleTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.PriceRuleSlice, error) {
	var err error
	m := make(models.PriceRuleSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// PriceRule has methods that act as mods for the PriceRuleTemplate
var PriceRuleMods priceRuleMods

type priceRuleMods struct{}

func (m priceRuleMods) RandomizeAllColumns(f *faker.Faker) PriceRuleMod {
	return PriceRuleModSlice{
		PriceRuleMods.RandomID(f),
		PriceRuleMods.RandomPricePeriodID(f),
		PriceRuleMods.RandomDayPattern(f),
		PriceRuleMods.RandomTimeStart(f),
		PriceRuleMods.RandomTimeEnd(f),
		PriceRuleMods.RandomPrice(f),
	}
}

// Set the model columns to this value
func (m priceRuleMods) ID(val int32) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) IDFunc(f func() int32) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetID() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomID(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m priceRuleMods) PricePeriodID(val int32) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.PricePeriodID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) PricePeriodIDFunc(f func() int32) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.PricePeriodID = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetPricePeriodID() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.PricePeriodID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomPricePeriodID(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.PricePeriodID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m priceRuleMods) DayPattern(val string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.DayPattern = func() string { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) DayPatternFunc(f func() string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.DayPattern = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetDayPattern() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.DayPattern = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomDayPattern(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.DayPattern = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m priceRuleMods) TimeStart(val string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeStart = func() string { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) TimeStartFunc(f func() string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeStart = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetTimeStart() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeStart = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomTimeStart(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeStart = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m priceRuleMods) TimeEnd(val string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeEnd = func() string { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) TimeEndFunc(f func() string) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeEnd = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetTimeEnd() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeEnd = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomTimeEnd(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.TimeEnd = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m priceRuleMods) Price(val decimal.Decimal) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.Price = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m priceRuleMods) PriceFunc(f func() decimal.Decimal) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m priceRuleMods) UnsetPrice() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m priceRuleMods) RandomPrice(f *faker.Faker) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.Price = func() decimal.Decimal {
			return random_decimal_Decimal(f)
		}
	})
}

func (m priceRuleMods) WithPricePeriod(rel *PricePeriodTemplate) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.r.PricePeriod = &priceRuleRPricePeriodR{
			o: rel,
		}
	})
}

func (m priceRuleMods) WithNewPricePeriod(mods ...PricePeriodMod) PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		related := o.f.NewPricePeriod(mods...)

		m.WithPricePeriod(related).Apply(o)
	})
}

func (m priceRuleMods) WithoutPricePeriod() PriceRuleMod {
	return PriceRuleModFunc(func(o *PriceRuleTemplate) {
		o.r.PricePeriod = nil
	})
}
