// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/xtp-tour/xtp-tour/api/pkg/db/models"
)

type PricePeriodMod interface {
	Apply(*PricePeriodTemplate)
}

type PricePeriodModFunc func(*PricePeriodTemplate)

func (f PricePeriodModFunc) Apply(n *PricePeriodTemplate) {
	f(n)
}

type PricePeriodModSlice []PricePeriodMod

func (mods PricePeriodModSlice) Apply(n *PricePeriodTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// PricePeriodTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type PricePeriodTemplate struct {
	ID           func() int32
	CourtGroupID func() int32
	ValidFrom    func() time.Time
	ValidTo      func() time.Time

	r pricePeriodR
	f *Factory
}

type pricePeriodR struct {
	CourtGroup *pricePeriodRCourtGroupR
	PriceRules []*pricePeriodRPriceRulesR
}

type pricePeriodRCourtGroupR struct {
	o *CourtGroupTemplate
}
type pricePeriodRPriceRulesR struct {
	number int
	o      *PriceRuleTemplate
}

// Apply mods to the PricePeriodTemplate
func (o *PricePeriodTemplate) Apply(mods ...PricePeriodMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.PricePeriod
// this does nothing with the relationship templates
func (o PricePeriodTemplate) toModel() *models.PricePeriod {
	m := &models.PricePeriod{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.CourtGroupID != nil {
		m.CourtGroupID = o.CourtGroupID()
	}
	if o.ValidFrom != nil {
		m.ValidFrom = o.ValidFrom()
	}
	if o.ValidTo != nil {
		m.ValidTo = o.ValidTo()
	}

	return m
}

// toModels returns an models.PricePeriodSlice
// this does nothing with the relationship templates
func (o PricePeriodTemplate) toModels(number int) models.PricePeriodSlice {
	m := make(models.PricePeriodSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.PricePeriod
// according to the relationships in the template. Nothing is inserted into the db
func (t PricePeriodTemplate) setModelRels(o *models.PricePeriod) {
	if t.r.CourtGroup != nil {
		rel := t.r.CourtGroup.o.toModel()
		rel.R.PricePeriods = append(rel.R.PricePeriods, o)
		o.CourtGroupID = rel.ID
		o.R.CourtGroup = rel
	}

	if t.r.PriceRules != nil {
		rel := models.PriceRuleSlice{}
		for _, r := range t.r.PriceRules {
			related := r.o.toModels(r.number)
			for _, rel := range related {
				rel.PricePeriodID = o.ID
				rel.R.PricePeriod = o
			}
			rel = append(rel, related...)
		}
		o.R.PriceRules = rel
	}
}

// BuildSetter returns an *models.PricePeriodSetter
// this does nothing with the relationship templates
func (o PricePeriodTemplate) BuildSetter() *models.PricePeriodSetter {
	m := &models.PricePeriodSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.CourtGroupID != nil {
		m.CourtGroupID = omit.From(o.CourtGroupID())
	}
	if o.ValidFrom != nil {
		m.ValidFrom = omit.From(o.ValidFrom())
	}
	if o.ValidTo != nil {
		m.ValidTo = omit.From(o.ValidTo())
	}

	return m
}

// BuildManySetter returns an []*models.PricePeriodSetter
// this does nothing with the relationship templates
func (o PricePeriodTemplate) BuildManySetter(number int) []*models.PricePeriodSetter {
	m := make([]*models.PricePeriodSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.PricePeriod
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PricePeriodTemplate.Create
func (o PricePeriodTemplate) Build() *models.PricePeriod {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.PricePeriodSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use PricePeriodTemplate.CreateMany
func (o PricePeriodTemplate) BuildMany(number int) models.PricePeriodSlice {
	m := make(models.PricePeriodSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatablePricePeriod(m *models.PricePeriodSetter) {
	if m.CourtGroupID.IsUnset() {
		m.CourtGroupID = omit.From(random_int32(nil))
	}
	if m.ValidFrom.IsUnset() {
		m.ValidFrom = omit.From(random_time_Time(nil))
	}
	if m.ValidTo.IsUnset() {
		m.ValidTo = omit.From(random_time_Time(nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.PricePeriod
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *PricePeriodTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.PricePeriod) (context.Context, error) {
	var err error

	if o.r.PriceRules != nil {
		for _, r := range o.r.PriceRules {
			var rel1 models.PriceRuleSlice
			ctx, rel1, err = r.o.createMany(ctx, exec, r.number)
			if err != nil {
				return ctx, err
			}

			err = m.AttachPriceRules(ctx, exec, rel1...)
			if err != nil {
				return ctx, err
			}
		}
	}

	return ctx, err
}

// Create builds a pricePeriod and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *PricePeriodTemplate) Create(ctx context.Context, exec bob.Executor) (*models.PricePeriod, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a pricePeriod and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *PricePeriodTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.PricePeriod {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a pricePeriod and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *PricePeriodTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.PricePeriod {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a pricePeriod and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *PricePeriodTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.PricePeriod, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatablePricePeriod(opt)

	var rel0 *models.CourtGroup
	if o.r.CourtGroup == nil {
		var ok bool
		rel0, ok = courtGroupCtx.Value(ctx)
		if !ok {
			PricePeriodMods.WithNewCourtGroup().Apply(o)
		}
	}
	if o.r.CourtGroup != nil {
		ctx, rel0, err = o.r.CourtGroup.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}
	opt.CourtGroupID = omit.From(rel0.ID)

	m, err := models.PricePeriods.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = pricePeriodCtx.WithValue(ctx, m)

	m.R.CourtGroup = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple pricePeriods and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o PricePeriodTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.PricePeriodSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple pricePeriods and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o PricePeriodTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.PricePeriodSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple pricePeriods and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o PricePeriodTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.PricePeriodSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple pricePeriods and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o PricePeriodTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.PricePeriodSlice, error) {
	var err error
	m := make(models.PricePeriodSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// PricePeriod has methods that act as mods for the PricePeriodTemplate
var PricePeriodMods pricePeriodMods

type pricePeriodMods struct{}

func (m pricePeriodMods) RandomizeAllColumns(f *faker.Faker) PricePeriodMod {
	return PricePeriodModSlice{
		PricePeriodMods.RandomID(f),
		PricePeriodMods.RandomCourtGroupID(f),
		PricePeriodMods.RandomValidFrom(f),
		PricePeriodMods.RandomValidTo(f),
	}
}

// Set the model columns to this value
func (m pricePeriodMods) ID(val int32) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m pricePeriodMods) IDFunc(f func() int32) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m pricePeriodMods) UnsetID() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pricePeriodMods) RandomID(f *faker.Faker) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m pricePeriodMods) CourtGroupID(val int32) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.CourtGroupID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m pricePeriodMods) CourtGroupIDFunc(f func() int32) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.CourtGroupID = f
	})
}

// Clear any values for the column
func (m pricePeriodMods) UnsetCourtGroupID() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.CourtGroupID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pricePeriodMods) RandomCourtGroupID(f *faker.Faker) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.CourtGroupID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m pricePeriodMods) ValidFrom(val time.Time) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidFrom = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m pricePeriodMods) ValidFromFunc(f func() time.Time) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidFrom = f
	})
}

// Clear any values for the column
func (m pricePeriodMods) UnsetValidFrom() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidFrom = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pricePeriodMods) RandomValidFrom(f *faker.Faker) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidFrom = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m pricePeriodMods) ValidTo(val time.Time) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidTo = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m pricePeriodMods) ValidToFunc(f func() time.Time) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidTo = f
	})
}

// Clear any values for the column
func (m pricePeriodMods) UnsetValidTo() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidTo = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m pricePeriodMods) RandomValidTo(f *faker.Faker) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.ValidTo = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m pricePeriodMods) WithCourtGroup(rel *CourtGroupTemplate) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.r.CourtGroup = &pricePeriodRCourtGroupR{
			o: rel,
		}
	})
}

func (m pricePeriodMods) WithNewCourtGroup(mods ...CourtGroupMod) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		related := o.f.NewCourtGroup(mods...)

		m.WithCourtGroup(related).Apply(o)
	})
}

func (m pricePeriodMods) WithoutCourtGroup() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.r.CourtGroup = nil
	})
}

func (m pricePeriodMods) WithPriceRules(number int, related *PriceRuleTemplate) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.r.PriceRules = []*pricePeriodRPriceRulesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m pricePeriodMods) WithNewPriceRules(number int, mods ...PriceRuleMod) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		related := o.f.NewPriceRule(mods...)
		m.WithPriceRules(number, related).Apply(o)
	})
}

func (m pricePeriodMods) AddPriceRules(number int, related *PriceRuleTemplate) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.r.PriceRules = append(o.r.PriceRules, &pricePeriodRPriceRulesR{
			number: number,
			o:      related,
		})
	})
}

func (m pricePeriodMods) AddNewPriceRules(number int, mods ...PriceRuleMod) PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		related := o.f.NewPriceRule(mods...)
		m.AddPriceRules(number, related).Apply(o)
	})
}

func (m pricePeriodMods) WithoutPriceRules() PricePeriodMod {
	return PricePeriodModFunc(func(o *PricePeriodTemplate) {
		o.r.PriceRules = nil
	})
}
