// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExpirationNotifier creates a new instance of MockExpirationNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpirationNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpirationNotifier {
	mock := &MockExpirationNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpirationNotifier is an autogenerated mock type for the ExpirationNotifier type
type MockExpirationNotifier struct {
	mock.Mock
}

type MockExpirationNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpirationNotifier) EXPECT() *MockExpirationNotifier_Expecter {
	return &MockExpirationNotifier_Expecter{mock: &_m.Mock}
}

// EventExpired provides a mock function for the type MockExpirationNotifier
func (_mock *MockExpirationNotifier) EventExpired(userId string, eventId string) {
	_mock.Called(userId, eventId)
	return
}

// MockExpirationNotifier_EventExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventExpired'
type MockExpirationNotifier_EventExpired_Call struct {
	*mock.Call
}

// EventExpired is a helper method to define mock.On call
//   - userId string
//   - eventId string
func (_e *MockExpirationNotifier_Expecter) EventExpired(userId interface{}, eventId interface{}) *MockExpirationNotifier_EventExpired_Call {
	return &MockExpirationNotifier_EventExpired_Call{Call: _e.mock.On("EventExpired", userId, eventId)}
}

func (_c *MockExpirationNotifier_EventExpired_Call) Run(run func(userId string, eventId string)) *MockExpirationNotifier_EventExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpirationNotifier_EventExpired_Call) Return() *MockExpirationNotifier_EventExpired_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExpirationNotifier_EventExpired_Call) RunAndReturn(run func(userId string, eventId string)) *MockExpirationNotifier_EventExpired_Call {
	_c.Run(run)
	return _c
}
