// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"hash/maphash"
	"strings"

	mysqlDriver "github.com/go-sql-driver/mysql"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
)

var TableNames = struct {
	ConfirmationJoinRequests string
	Confirmations            string
	CourtGroups              string
	EventLocations           string
	EventTimeSlots           string
	Events                   string
	Facilities               string
	FacilityPartnerCards     string
	JoinRequestLocations     string
	JoinRequestTimeSlots     string
	JoinRequests             string
	PartnerCards             string
	PricePeriods             string
	PriceRules               string
	SchemaMigrations         string
	UserPrefs                string
	Users                    string
}{
	ConfirmationJoinRequests: "confirmation_join_requests",
	Confirmations:            "confirmations",
	CourtGroups:              "court_groups",
	EventLocations:           "event_locations",
	EventTimeSlots:           "event_time_slots",
	Events:                   "events",
	Facilities:               "facilities",
	FacilityPartnerCards:     "facility_partner_cards",
	JoinRequestLocations:     "join_request_locations",
	JoinRequestTimeSlots:     "join_request_time_slots",
	JoinRequests:             "join_requests",
	PartnerCards:             "partner_cards",
	PricePeriods:             "price_periods",
	PriceRules:               "price_rules",
	SchemaMigrations:         "schema_migrations",
	UserPrefs:                "user_pref",
	Users:                    "users",
}

var ColumnNames = struct {
	ConfirmationJoinRequests confirmationJoinRequestColumnNames
	Confirmations            confirmationColumnNames
	CourtGroups              courtGroupColumnNames
	EventLocations           eventLocationColumnNames
	EventTimeSlots           eventTimeSlotColumnNames
	Events                   eventColumnNames
	Facilities               facilityColumnNames
	FacilityPartnerCards     facilityPartnerCardColumnNames
	JoinRequestLocations     joinRequestLocationColumnNames
	JoinRequestTimeSlots     joinRequestTimeSlotColumnNames
	JoinRequests             joinRequestColumnNames
	PartnerCards             partnerCardColumnNames
	PricePeriods             pricePeriodColumnNames
	PriceRules               priceRuleColumnNames
	SchemaMigrations         schemaMigrationColumnNames
	UserPrefs                userPrefColumnNames
	Users                    userColumnNames
}{
	ConfirmationJoinRequests: confirmationJoinRequestColumnNames{
		ConfirmationID: "confirmation_id",
		JoinRequestID:  "join_request_id",
	},
	Confirmations: confirmationColumnNames{
		ID:         "id",
		EventID:    "event_id",
		LocationID: "location_id",
		Date:       "date",
		Time:       "time",
		Duration:   "duration",
		CreatedAt:  "created_at",
	},
	CourtGroups: courtGroupColumnNames{
		ID:              "id",
		FacilityID:      "facility_id",
		Surface:         "surface",
		Type:            "type",
		Light:           "light",
		Heating:         "heating",
		ReservationLink: "reservation_link",
		CourtNames:      "court_names",
	},
	EventLocations: eventLocationColumnNames{
		EventID:    "event_id",
		LocationID: "location_id",
	},
	EventTimeSlots: eventTimeSlotColumnNames{
		ID:      "id",
		EventID: "event_id",
		Date:    "date",
		Time:    "time",
	},
	Events: eventColumnNames{
		ID:              "id",
		UserID:          "user_id",
		SkillLevel:      "skill_level",
		Description:     "description",
		EventType:       "event_type",
		ExpectedPlayers: "expected_players",
		SessionDuration: "session_duration",
		Status:          "status",
		CreatedAt:       "created_at",
		UpdatedAt:       "updated_at",
	},
	Facilities: facilityColumnNames{
		ID:             "id",
		Name:           "name",
		Address:        "address",
		GoogleMapsLink: "google_maps_link",
		Website:        "website",
		Country:        "country",
		Location:       "location",
	},
	FacilityPartnerCards: facilityPartnerCardColumnNames{
		FacilityID:    "facility_id",
		PartnerCardID: "partner_card_id",
	},
	JoinRequestLocations: joinRequestLocationColumnNames{
		JoinRequestID: "join_request_id",
		LocationID:    "location_id",
	},
	JoinRequestTimeSlots: joinRequestTimeSlotColumnNames{
		ID:            "id",
		JoinRequestID: "join_request_id",
		Date:          "date",
		Time:          "time",
	},
	JoinRequests: joinRequestColumnNames{
		ID:        "id",
		EventID:   "event_id",
		UserID:    "user_id",
		Status:    "status",
		Comment:   "comment",
		CreatedAt: "created_at",
	},
	PartnerCards: partnerCardColumnNames{
		ID:   "id",
		Name: "name",
	},
	PricePeriods: pricePeriodColumnNames{
		ID:           "id",
		CourtGroupID: "court_group_id",
		ValidFrom:    "valid_from",
		ValidTo:      "valid_to",
	},
	PriceRules: priceRuleColumnNames{
		ID:            "id",
		PricePeriodID: "price_period_id",
		DayPattern:    "day_pattern",
		TimeStart:     "time_start",
		TimeEnd:       "time_end",
		Price:         "price",
	},
	SchemaMigrations: schemaMigrationColumnNames{
		Version: "version",
		Dirty:   "dirty",
	},
	UserPrefs: userPrefColumnNames{
		UID:      "uid",
		Language: "language",
		Country:  "country",
		City:     "city",
	},
	Users: userColumnNames{
		UID:         "uid",
		PhoneNumber: "phone_number",
		Country:     "country",
		ExternalID:  "external_id",
		CreatedAt:   "created_at",
		UpdatedAt:   "updated_at",
	},
}

var (
	SelectWhere = Where[*dialect.SelectQuery]()
	UpdateWhere = Where[*dialect.UpdateQuery]()
	DeleteWhere = Where[*dialect.DeleteQuery]()
)

func Where[Q mysql.Filterable]() struct {
	ConfirmationJoinRequests confirmationJoinRequestWhere[Q]
	Confirmations            confirmationWhere[Q]
	CourtGroups              courtGroupWhere[Q]
	EventLocations           eventLocationWhere[Q]
	EventTimeSlots           eventTimeSlotWhere[Q]
	Events                   eventWhere[Q]
	Facilities               facilityWhere[Q]
	FacilityPartnerCards     facilityPartnerCardWhere[Q]
	JoinRequestLocations     joinRequestLocationWhere[Q]
	JoinRequestTimeSlots     joinRequestTimeSlotWhere[Q]
	JoinRequests             joinRequestWhere[Q]
	PartnerCards             partnerCardWhere[Q]
	PricePeriods             pricePeriodWhere[Q]
	PriceRules               priceRuleWhere[Q]
	SchemaMigrations         schemaMigrationWhere[Q]
	UserPrefs                userPrefWhere[Q]
	Users                    userWhere[Q]
} {
	return struct {
		ConfirmationJoinRequests confirmationJoinRequestWhere[Q]
		Confirmations            confirmationWhere[Q]
		CourtGroups              courtGroupWhere[Q]
		EventLocations           eventLocationWhere[Q]
		EventTimeSlots           eventTimeSlotWhere[Q]
		Events                   eventWhere[Q]
		Facilities               facilityWhere[Q]
		FacilityPartnerCards     facilityPartnerCardWhere[Q]
		JoinRequestLocations     joinRequestLocationWhere[Q]
		JoinRequestTimeSlots     joinRequestTimeSlotWhere[Q]
		JoinRequests             joinRequestWhere[Q]
		PartnerCards             partnerCardWhere[Q]
		PricePeriods             pricePeriodWhere[Q]
		PriceRules               priceRuleWhere[Q]
		SchemaMigrations         schemaMigrationWhere[Q]
		UserPrefs                userPrefWhere[Q]
		Users                    userWhere[Q]
	}{
		ConfirmationJoinRequests: buildConfirmationJoinRequestWhere[Q](ConfirmationJoinRequestColumns),
		Confirmations:            buildConfirmationWhere[Q](ConfirmationColumns),
		CourtGroups:              buildCourtGroupWhere[Q](CourtGroupColumns),
		EventLocations:           buildEventLocationWhere[Q](EventLocationColumns),
		EventTimeSlots:           buildEventTimeSlotWhere[Q](EventTimeSlotColumns),
		Events:                   buildEventWhere[Q](EventColumns),
		Facilities:               buildFacilityWhere[Q](FacilityColumns),
		FacilityPartnerCards:     buildFacilityPartnerCardWhere[Q](FacilityPartnerCardColumns),
		JoinRequestLocations:     buildJoinRequestLocationWhere[Q](JoinRequestLocationColumns),
		JoinRequestTimeSlots:     buildJoinRequestTimeSlotWhere[Q](JoinRequestTimeSlotColumns),
		JoinRequests:             buildJoinRequestWhere[Q](JoinRequestColumns),
		PartnerCards:             buildPartnerCardWhere[Q](PartnerCardColumns),
		PricePeriods:             buildPricePeriodWhere[Q](PricePeriodColumns),
		PriceRules:               buildPriceRuleWhere[Q](PriceRuleColumns),
		SchemaMigrations:         buildSchemaMigrationWhere[Q](SchemaMigrationColumns),
		UserPrefs:                buildUserPrefWhere[Q](UserPrefColumns),
		Users:                    buildUserWhere[Q](UserColumns),
	}
}

var (
	SelectJoins = getJoins[*dialect.SelectQuery]()
	UpdateJoins = getJoins[*dialect.UpdateQuery]()
	DeleteJoins = getJoins[*dialect.DeleteQuery]()
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	ConfirmationJoinRequests joinSet[confirmationJoinRequestJoins[Q]]
	Confirmations            joinSet[confirmationJoins[Q]]
	CourtGroups              joinSet[courtGroupJoins[Q]]
	EventLocations           joinSet[eventLocationJoins[Q]]
	EventTimeSlots           joinSet[eventTimeSlotJoins[Q]]
	Events                   joinSet[eventJoins[Q]]
	Facilities               joinSet[facilityJoins[Q]]
	FacilityPartnerCards     joinSet[facilityPartnerCardJoins[Q]]
	JoinRequestLocations     joinSet[joinRequestLocationJoins[Q]]
	JoinRequestTimeSlots     joinSet[joinRequestTimeSlotJoins[Q]]
	JoinRequests             joinSet[joinRequestJoins[Q]]
	PartnerCards             joinSet[partnerCardJoins[Q]]
	PricePeriods             joinSet[pricePeriodJoins[Q]]
	PriceRules               joinSet[priceRuleJoins[Q]]
	UserPrefs                joinSet[userPrefJoins[Q]]
	Users                    joinSet[userJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		ConfirmationJoinRequests: buildJoinSet[confirmationJoinRequestJoins[Q]](ConfirmationJoinRequestColumns, buildConfirmationJoinRequestJoins),
		Confirmations:            buildJoinSet[confirmationJoins[Q]](ConfirmationColumns, buildConfirmationJoins),
		CourtGroups:              buildJoinSet[courtGroupJoins[Q]](CourtGroupColumns, buildCourtGroupJoins),
		EventLocations:           buildJoinSet[eventLocationJoins[Q]](EventLocationColumns, buildEventLocationJoins),
		EventTimeSlots:           buildJoinSet[eventTimeSlotJoins[Q]](EventTimeSlotColumns, buildEventTimeSlotJoins),
		Events:                   buildJoinSet[eventJoins[Q]](EventColumns, buildEventJoins),
		Facilities:               buildJoinSet[facilityJoins[Q]](FacilityColumns, buildFacilityJoins),
		FacilityPartnerCards:     buildJoinSet[facilityPartnerCardJoins[Q]](FacilityPartnerCardColumns, buildFacilityPartnerCardJoins),
		JoinRequestLocations:     buildJoinSet[joinRequestLocationJoins[Q]](JoinRequestLocationColumns, buildJoinRequestLocationJoins),
		JoinRequestTimeSlots:     buildJoinSet[joinRequestTimeSlotJoins[Q]](JoinRequestTimeSlotColumns, buildJoinRequestTimeSlotJoins),
		JoinRequests:             buildJoinSet[joinRequestJoins[Q]](JoinRequestColumns, buildJoinRequestJoins),
		PartnerCards:             buildJoinSet[partnerCardJoins[Q]](PartnerCardColumns, buildPartnerCardJoins),
		PricePeriods:             buildJoinSet[pricePeriodJoins[Q]](PricePeriodColumns, buildPricePeriodJoins),
		PriceRules:               buildJoinSet[priceRuleJoins[Q]](PriceRuleColumns, buildPriceRuleJoins),
		UserPrefs:                buildJoinSet[userPrefJoins[Q]](UserPrefColumns, buildUserPrefJoins),
		Users:                    buildJoinSet[userJoins[Q]](UserColumns, buildUserJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}

// ErrUniqueConstraint captures all unique constraint errors by explicitly leaving `s` empty.
var ErrUniqueConstraint = &UniqueConstraintError{s: ""}

type UniqueConstraintError struct {
	// s is a string uniquely identifying the constraint in the raw error message returned from the database.
	s string
}

func (e *UniqueConstraintError) Error() string {
	return e.s
}

func (e *UniqueConstraintError) Is(target error) bool {
	err, ok := target.(*mysqlDriver.MySQLError)
	if !ok {
		return false
	}
	return err.Number == 1062 && strings.Contains(err.Message, e.s)
}
