// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

// Make sure the type ConfirmationJoinRequest runs hooks after queries
var _ bob.HookableType = &ConfirmationJoinRequest{}

// Make sure the type Confirmation runs hooks after queries
var _ bob.HookableType = &Confirmation{}

// Make sure the type CourtGroup runs hooks after queries
var _ bob.HookableType = &CourtGroup{}

// Make sure the type EventLocation runs hooks after queries
var _ bob.HookableType = &EventLocation{}

// Make sure the type EventTimeSlot runs hooks after queries
var _ bob.HookableType = &EventTimeSlot{}

// Make sure the type Event runs hooks after queries
var _ bob.HookableType = &Event{}

// Make sure the type Facility runs hooks after queries
var _ bob.HookableType = &Facility{}

// Make sure the type FacilityPartnerCard runs hooks after queries
var _ bob.HookableType = &FacilityPartnerCard{}

// Make sure the type JoinRequestLocation runs hooks after queries
var _ bob.HookableType = &JoinRequestLocation{}

// Make sure the type JoinRequestTimeSlot runs hooks after queries
var _ bob.HookableType = &JoinRequestTimeSlot{}

// Make sure the type JoinRequest runs hooks after queries
var _ bob.HookableType = &JoinRequest{}

// Make sure the type PartnerCard runs hooks after queries
var _ bob.HookableType = &PartnerCard{}

// Make sure the type PricePeriod runs hooks after queries
var _ bob.HookableType = &PricePeriod{}

// Make sure the type PriceRule runs hooks after queries
var _ bob.HookableType = &PriceRule{}

// Make sure the type SchemaMigration runs hooks after queries
var _ bob.HookableType = &SchemaMigration{}

// Make sure the type UserPref runs hooks after queries
var _ bob.HookableType = &UserPref{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type CourtGroupsSurface satisfies database/sql.Scanner
var _ sql.Scanner = (*CourtGroupsSurface)(nil)

// Make sure the type CourtGroupsSurface satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(CourtGroupsSurface)

// Make sure the type CourtGroupsType satisfies database/sql.Scanner
var _ sql.Scanner = (*CourtGroupsType)(nil)

// Make sure the type CourtGroupsType satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(CourtGroupsType)

// Make sure the type EventsSkillLevel satisfies database/sql.Scanner
var _ sql.Scanner = (*EventsSkillLevel)(nil)

// Make sure the type EventsSkillLevel satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(EventsSkillLevel)

// Make sure the type EventsEventType satisfies database/sql.Scanner
var _ sql.Scanner = (*EventsEventType)(nil)

// Make sure the type EventsEventType satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(EventsEventType)

// Make sure the type EventsStatus satisfies database/sql.Scanner
var _ sql.Scanner = (*EventsStatus)(nil)

// Make sure the type EventsStatus satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(EventsStatus)

// Make sure the type JoinRequestsStatus satisfies database/sql.Scanner
var _ sql.Scanner = (*JoinRequestsStatus)(nil)

// Make sure the type JoinRequestsStatus satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(JoinRequestsStatus)

// Make sure the type decimal.Decimal satisfies database/sql.Scanner
var _ sql.Scanner = (*decimal.Decimal)(nil)

// Make sure the type decimal.Decimal satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(decimal.Decimal)
