// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// EventLocation is an object representing the database table.
type EventLocation struct {
	EventID    string `db:"event_id,pk" `
	LocationID string `db:"location_id,pk" `

	R eventLocationR `db:"-" `
}

// EventLocationSlice is an alias for a slice of pointers to EventLocation.
// This should almost always be used instead of []*EventLocation.
type EventLocationSlice []*EventLocation

// EventLocations contains methods to work with the event_locations table
var EventLocations = mysql.NewTablex[*EventLocation, EventLocationSlice, *EventLocationSetter]("event_locations", []string{"event_id", "location_id"})

// EventLocationsQuery is a query on the event_locations table
type EventLocationsQuery = *mysql.ViewQuery[*EventLocation, EventLocationSlice]

// eventLocationR is where relationships are stored.
type eventLocationR struct {
	Event            *Event    // event_locations_ibfk_1
	LocationFacility *Facility // event_locations_ibfk_2
}

type eventLocationColumnNames struct {
	EventID    string
	LocationID string
}

var EventLocationColumns = buildEventLocationColumns("event_locations")

type eventLocationColumns struct {
	tableAlias string
	EventID    mysql.Expression
	LocationID mysql.Expression
}

func (c eventLocationColumns) Alias() string {
	return c.tableAlias
}

func (eventLocationColumns) AliasedAs(alias string) eventLocationColumns {
	return buildEventLocationColumns(alias)
}

func buildEventLocationColumns(alias string) eventLocationColumns {
	return eventLocationColumns{
		tableAlias: alias,
		EventID:    mysql.Quote(alias, "event_id"),
		LocationID: mysql.Quote(alias, "location_id"),
	}
}

type eventLocationWhere[Q mysql.Filterable] struct {
	EventID    mysql.WhereMod[Q, string]
	LocationID mysql.WhereMod[Q, string]
}

func (eventLocationWhere[Q]) AliasedAs(alias string) eventLocationWhere[Q] {
	return buildEventLocationWhere[Q](buildEventLocationColumns(alias))
}

func buildEventLocationWhere[Q mysql.Filterable](cols eventLocationColumns) eventLocationWhere[Q] {
	return eventLocationWhere[Q]{
		EventID:    mysql.Where[Q, string](cols.EventID),
		LocationID: mysql.Where[Q, string](cols.LocationID),
	}
}

var EventLocationErrors = &eventLocationErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type eventLocationErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// EventLocationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type EventLocationSetter struct {
	EventID    omit.Val[string] `db:"event_id,pk" `
	LocationID omit.Val[string] `db:"location_id,pk" `
}

func (s EventLocationSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if !s.EventID.IsUnset() {
		vals = append(vals, "event_id")
	}

	if !s.LocationID.IsUnset() {
		vals = append(vals, "location_id")
	}

	return vals
}

func (s EventLocationSetter) Overwrite(t *EventLocation) {
	if !s.EventID.IsUnset() {
		t.EventID, _ = s.EventID.Get()
	}
	if !s.LocationID.IsUnset() {
		t.LocationID, _ = s.LocationID.Get()
	}
}

func (s *EventLocationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return EventLocations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.EventID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.EventID)
		}

		if s.LocationID.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.LocationID)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s EventLocationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("event_locations")...)
}

func (s EventLocationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if !s.EventID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "event_id")...),
			mysql.Arg(s.EventID),
		}})
	}

	if !s.LocationID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "location_id")...),
			mysql.Arg(s.LocationID),
		}})
	}

	return exprs
}

// FindEventLocation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindEventLocation(ctx context.Context, exec bob.Executor, EventIDPK string, LocationIDPK string, cols ...string) (*EventLocation, error) {
	if len(cols) == 0 {
		return EventLocations.Query(
			SelectWhere.EventLocations.EventID.EQ(EventIDPK),
			SelectWhere.EventLocations.LocationID.EQ(LocationIDPK),
		).One(ctx, exec)
	}

	return EventLocations.Query(
		SelectWhere.EventLocations.EventID.EQ(EventIDPK),
		SelectWhere.EventLocations.LocationID.EQ(LocationIDPK),
		sm.Columns(EventLocations.Columns().Only(cols...)),
	).One(ctx, exec)
}

// EventLocationExists checks the presence of a single record by primary key
func EventLocationExists(ctx context.Context, exec bob.Executor, EventIDPK string, LocationIDPK string) (bool, error) {
	return EventLocations.Query(
		SelectWhere.EventLocations.EventID.EQ(EventIDPK),
		SelectWhere.EventLocations.LocationID.EQ(LocationIDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after EventLocation is retrieved from the database
func (o *EventLocation) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EventLocations.AfterSelectHooks.RunHooks(ctx, exec, EventLocationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = EventLocations.AfterInsertHooks.RunHooks(ctx, exec, EventLocationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = EventLocations.AfterUpdateHooks.RunHooks(ctx, exec, EventLocationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = EventLocations.AfterDeleteHooks.RunHooks(ctx, exec, EventLocationSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the EventLocation
func (o *EventLocation) PrimaryKeyVals() bob.Expression {
	return mysql.ArgGroup(
		o.EventID,
		o.LocationID,
	)
}

func (o *EventLocation) pkEQ() dialect.Expression {
	return mysql.Group(mysql.Quote("event_locations", "event_id"), mysql.Quote("event_locations", "location_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the EventLocation
func (o *EventLocation) Update(ctx context.Context, exec bob.Executor, s *EventLocationSetter) error {
	_, err := EventLocations.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single EventLocation record with an executor
func (o *EventLocation) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := EventLocations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the EventLocation using the executor
func (o *EventLocation) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := EventLocations.Query(
		SelectWhere.EventLocations.EventID.EQ(o.EventID),
		SelectWhere.EventLocations.LocationID.EQ(o.LocationID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after EventLocationSlice is retrieved from the database
func (o EventLocationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = EventLocations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = EventLocations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = EventLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = EventLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o EventLocationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Group(mysql.Quote("event_locations", "event_id"), mysql.Quote("event_locations", "location_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o EventLocationSlice) copyMatchingRows(from ...*EventLocation) {
	for i, old := range o {
		for _, new := range from {
			if new.EventID != old.EventID {
				continue
			}
			if new.LocationID != old.LocationID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o EventLocationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EventLocations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EventLocation:
				o.copyMatchingRows(retrieved)
			case []*EventLocation:
				o.copyMatchingRows(retrieved...)
			case EventLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EventLocation or a slice of EventLocation
				// then run the AfterUpdateHooks on the slice
				_, err = EventLocations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o EventLocationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return EventLocations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *EventLocation:
				o.copyMatchingRows(retrieved)
			case []*EventLocation:
				o.copyMatchingRows(retrieved...)
			case EventLocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a EventLocation or a slice of EventLocation
				// then run the AfterDeleteHooks on the slice
				_, err = EventLocations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o EventLocationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals EventLocationSetter) error {
	_, err := EventLocations.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o EventLocationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := EventLocations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o EventLocationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := EventLocations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type eventLocationJoins[Q dialect.Joinable] struct {
	typ              string
	Event            func(context.Context) modAs[Q, eventColumns]
	LocationFacility func(context.Context) modAs[Q, facilityColumns]
}

func (j eventLocationJoins[Q]) aliasedAs(alias string) eventLocationJoins[Q] {
	return buildEventLocationJoins[Q](buildEventLocationColumns(alias), j.typ)
}

func buildEventLocationJoins[Q dialect.Joinable](cols eventLocationColumns, typ string) eventLocationJoins[Q] {
	return eventLocationJoins[Q]{
		typ:              typ,
		Event:            eventLocationsJoinEvent[Q](cols, typ),
		LocationFacility: eventLocationsJoinLocationFacility[Q](cols, typ),
	}
}

func eventLocationsJoinEvent[Q dialect.Joinable](from eventLocationColumns, typ string) func(context.Context) modAs[Q, eventColumns] {
	return func(ctx context.Context) modAs[Q, eventColumns] {
		return modAs[Q, eventColumns]{
			c: EventColumns,
			f: func(to eventColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Events.Name().As(to.Alias())).On(
						to.ID.EQ(from.EventID),
					))
				}

				return mods
			},
		}
	}
}

func eventLocationsJoinLocationFacility[Q dialect.Joinable](from eventLocationColumns, typ string) func(context.Context) modAs[Q, facilityColumns] {
	return func(ctx context.Context) modAs[Q, facilityColumns] {
		return modAs[Q, facilityColumns]{
			c: FacilityColumns,
			f: func(to facilityColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Facilities.Name().As(to.Alias())).On(
						to.ID.EQ(from.LocationID),
					))
				}

				return mods
			},
		}
	}
}

// Event starts a query for related objects on events
func (o *EventLocation) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	return Events.Query(append(mods,
		sm.Where(EventColumns.ID.EQ(mysql.Arg(o.EventID))),
	)...)
}

func (os EventLocationSlice) Event(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.EventID)
	}

	return Events.Query(append(mods,
		sm.Where(mysql.Group(EventColumns.ID).In(PKArgs...)),
	)...)
}

// LocationFacility starts a query for related objects on facilities
func (o *EventLocation) LocationFacility(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	return Facilities.Query(append(mods,
		sm.Where(FacilityColumns.ID.EQ(mysql.Arg(o.LocationID))),
	)...)
}

func (os EventLocationSlice) LocationFacility(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.LocationID)
	}

	return Facilities.Query(append(mods,
		sm.Where(mysql.Group(FacilityColumns.ID).In(PKArgs...)),
	)...)
}

func (o *EventLocation) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Event":
		rel, ok := retrieved.(*Event)
		if !ok {
			return fmt.Errorf("eventLocation cannot load %T as %q", retrieved, name)
		}

		o.R.Event = rel

		return nil
	case "LocationFacility":
		rel, ok := retrieved.(*Facility)
		if !ok {
			return fmt.Errorf("eventLocation cannot load %T as %q", retrieved, name)
		}

		o.R.LocationFacility = rel

		return nil
	default:
		return fmt.Errorf("eventLocation has no relationship %q", name)
	}
}

func PreloadEventLocationEvent(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*Event, EventSlice](orm.Relationship{
		Name: "Event",
		Sides: []orm.RelSide{
			{
				From: TableNames.EventLocations,
				To:   TableNames.Events,
				FromColumns: []string{
					ColumnNames.EventLocations.EventID,
				},
				ToColumns: []string{
					ColumnNames.Events.ID,
				},
			},
		},
	}, Events.Columns().Names(), opts...)
}

func ThenLoadEventLocationEvent(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadEventLocationEvent(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load EventLocationEvent", retrieved)
		}

		err := loader.LoadEventLocationEvent(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadEventLocationEvent loads the eventLocation's Event into the .R struct
func (o *EventLocation) LoadEventLocationEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Event = nil

	related, err := o.Event(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Event = related
	return nil
}

// LoadEventLocationEvent loads the eventLocation's Event into the .R struct
func (os EventLocationSlice) LoadEventLocationEvent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	events, err := os.Event(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range events {
			if o.EventID != rel.ID {
				continue
			}

			o.R.Event = rel
			break
		}
	}

	return nil
}

func PreloadEventLocationLocationFacility(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*Facility, FacilitySlice](orm.Relationship{
		Name: "LocationFacility",
		Sides: []orm.RelSide{
			{
				From: TableNames.EventLocations,
				To:   TableNames.Facilities,
				FromColumns: []string{
					ColumnNames.EventLocations.LocationID,
				},
				ToColumns: []string{
					ColumnNames.Facilities.ID,
				},
			},
		},
	}, Facilities.Columns().Names(), opts...)
}

func ThenLoadEventLocationLocationFacility(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadEventLocationLocationFacility(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load EventLocationLocationFacility", retrieved)
		}

		err := loader.LoadEventLocationLocationFacility(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadEventLocationLocationFacility loads the eventLocation's LocationFacility into the .R struct
func (o *EventLocation) LoadEventLocationLocationFacility(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.LocationFacility = nil

	related, err := o.LocationFacility(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.LocationFacility = related
	return nil
}

// LoadEventLocationLocationFacility loads the eventLocation's LocationFacility into the .R struct
func (os EventLocationSlice) LoadEventLocationLocationFacility(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	facilities, err := os.LocationFacility(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range facilities {
			if o.LocationID != rel.ID {
				continue
			}

			o.R.LocationFacility = rel
			break
		}
	}

	return nil
}

func attachEventLocationEvent0(ctx context.Context, exec bob.Executor, count int, eventLocation0 *EventLocation, event1 *Event) (*EventLocation, error) {
	setter := &EventLocationSetter{
		EventID: omit.From(event1.ID),
	}

	err := eventLocation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachEventLocationEvent0: %w", err)
	}

	return eventLocation0, nil
}

func (eventLocation0 *EventLocation) InsertEvent(ctx context.Context, exec bob.Executor, related *EventSetter) error {
	event1, err := Events.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachEventLocationEvent0(ctx, exec, 1, eventLocation0, event1)
	if err != nil {
		return err
	}

	eventLocation0.R.Event = event1

	return nil
}

func (eventLocation0 *EventLocation) AttachEvent(ctx context.Context, exec bob.Executor, event1 *Event) error {
	var err error

	_, err = attachEventLocationEvent0(ctx, exec, 1, eventLocation0, event1)
	if err != nil {
		return err
	}

	eventLocation0.R.Event = event1

	return nil
}

func attachEventLocationLocationFacility0(ctx context.Context, exec bob.Executor, count int, eventLocation0 *EventLocation, facility1 *Facility) (*EventLocation, error) {
	setter := &EventLocationSetter{
		LocationID: omit.From(facility1.ID),
	}

	err := eventLocation0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachEventLocationLocationFacility0: %w", err)
	}

	return eventLocation0, nil
}

func (eventLocation0 *EventLocation) InsertLocationFacility(ctx context.Context, exec bob.Executor, related *FacilitySetter) error {
	facility1, err := Facilities.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachEventLocationLocationFacility0(ctx, exec, 1, eventLocation0, facility1)
	if err != nil {
		return err
	}

	eventLocation0.R.LocationFacility = facility1

	return nil
}

func (eventLocation0 *EventLocation) AttachLocationFacility(ctx context.Context, exec bob.Executor, facility1 *Facility) error {
	var err error

	_, err = attachEventLocationLocationFacility0(ctx, exec, 1, eventLocation0, facility1)
	if err != nil {
		return err
	}

	eventLocation0.R.LocationFacility = facility1

	return nil
}
