// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"strconv"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/scan"
)

// Facility is an object representing the database table.
type Facility struct {
	ID             string           `db:"id,pk" `
	Name           string           `db:"name" `
	Address        string           `db:"address" `
	GoogleMapsLink null.Val[string] `db:"google_maps_link" `
	Website        null.Val[string] `db:"website" `
	Country        string           `db:"country" `
	Location       string           `db:"location" `

	R facilityR `db:"-" `
}

// FacilitySlice is an alias for a slice of pointers to Facility.
// This should almost always be used instead of []*Facility.
type FacilitySlice []*Facility

// Facilities contains methods to work with the facilities table
var Facilities = mysql.NewTablex[*Facility, FacilitySlice, *FacilitySetter]("facilities", []string{"id"})

// FacilitiesQuery is a query on the facilities table
type FacilitiesQuery = *mysql.ViewQuery[*Facility, FacilitySlice]

// facilityR is where relationships are stored.
type facilityR struct {
	LocationConfirmations ConfirmationSlice // confirmations_ibfk_2
	CourtGroups           CourtGroupSlice   // court_groups_ibfk_1
	Events                EventSlice        // event_locations_ibfk_1event_locations_ibfk_2
	PartnerCards          PartnerCardSlice  // facility_partner_cards_ibfk_1facility_partner_cards_ibfk_2
	JoinRequests          JoinRequestSlice  // join_request_locations_ibfk_1join_request_locations_ibfk_2
}

type facilityColumnNames struct {
	ID             string
	Name           string
	Address        string
	GoogleMapsLink string
	Website        string
	Country        string
	Location       string
}

var FacilityColumns = buildFacilityColumns("facilities")

type facilityColumns struct {
	tableAlias     string
	ID             mysql.Expression
	Name           mysql.Expression
	Address        mysql.Expression
	GoogleMapsLink mysql.Expression
	Website        mysql.Expression
	Country        mysql.Expression
	Location       mysql.Expression
}

func (c facilityColumns) Alias() string {
	return c.tableAlias
}

func (facilityColumns) AliasedAs(alias string) facilityColumns {
	return buildFacilityColumns(alias)
}

func buildFacilityColumns(alias string) facilityColumns {
	return facilityColumns{
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		Name:           mysql.Quote(alias, "name"),
		Address:        mysql.Quote(alias, "address"),
		GoogleMapsLink: mysql.Quote(alias, "google_maps_link"),
		Website:        mysql.Quote(alias, "website"),
		Country:        mysql.Quote(alias, "country"),
		Location:       mysql.Quote(alias, "location"),
	}
}

type facilityWhere[Q mysql.Filterable] struct {
	ID             mysql.WhereMod[Q, string]
	Name           mysql.WhereMod[Q, string]
	Address        mysql.WhereMod[Q, string]
	GoogleMapsLink mysql.WhereNullMod[Q, string]
	Website        mysql.WhereNullMod[Q, string]
	Country        mysql.WhereMod[Q, string]
	Location       mysql.WhereMod[Q, string]
}

func (facilityWhere[Q]) AliasedAs(alias string) facilityWhere[Q] {
	return buildFacilityWhere[Q](buildFacilityColumns(alias))
}

func buildFacilityWhere[Q mysql.Filterable](cols facilityColumns) facilityWhere[Q] {
	return facilityWhere[Q]{
		ID:             mysql.Where[Q, string](cols.ID),
		Name:           mysql.Where[Q, string](cols.Name),
		Address:        mysql.Where[Q, string](cols.Address),
		GoogleMapsLink: mysql.WhereNull[Q, string](cols.GoogleMapsLink),
		Website:        mysql.WhereNull[Q, string](cols.Website),
		Country:        mysql.Where[Q, string](cols.Country),
		Location:       mysql.Where[Q, string](cols.Location),
	}
}

var FacilityErrors = &facilityErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type facilityErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// FacilitySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FacilitySetter struct {
	ID             omit.Val[string]     `db:"id,pk" `
	Name           omit.Val[string]     `db:"name" `
	Address        omit.Val[string]     `db:"address" `
	GoogleMapsLink omitnull.Val[string] `db:"google_maps_link" `
	Website        omitnull.Val[string] `db:"website" `
	Country        omit.Val[string]     `db:"country" `
	Location       omit.Val[string]     `db:"location" `
}

func (s FacilitySetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}

	if !s.Address.IsUnset() {
		vals = append(vals, "address")
	}

	if !s.GoogleMapsLink.IsUnset() {
		vals = append(vals, "google_maps_link")
	}

	if !s.Website.IsUnset() {
		vals = append(vals, "website")
	}

	if !s.Country.IsUnset() {
		vals = append(vals, "country")
	}

	if !s.Location.IsUnset() {
		vals = append(vals, "location")
	}

	return vals
}

func (s FacilitySetter) Overwrite(t *Facility) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.Name.IsUnset() {
		t.Name, _ = s.Name.Get()
	}
	if !s.Address.IsUnset() {
		t.Address, _ = s.Address.Get()
	}
	if !s.GoogleMapsLink.IsUnset() {
		t.GoogleMapsLink, _ = s.GoogleMapsLink.GetNull()
	}
	if !s.Website.IsUnset() {
		t.Website, _ = s.Website.GetNull()
	}
	if !s.Country.IsUnset() {
		t.Country, _ = s.Country.Get()
	}
	if !s.Location.IsUnset() {
		t.Location, _ = s.Location.Get()
	}
}

func (s *FacilitySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Facilities.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.ID)
		}

		if s.Name.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.Name)
		}

		if s.Address.IsUnset() {
			vals[2] = mysql.Raw("DEFAULT")
		} else {
			vals[2] = mysql.Arg(s.Address)
		}

		if s.GoogleMapsLink.IsUnset() {
			vals[3] = mysql.Raw("DEFAULT")
		} else {
			vals[3] = mysql.Arg(s.GoogleMapsLink)
		}

		if s.Website.IsUnset() {
			vals[4] = mysql.Raw("DEFAULT")
		} else {
			vals[4] = mysql.Arg(s.Website)
		}

		if s.Country.IsUnset() {
			vals[5] = mysql.Raw("DEFAULT")
		} else {
			vals[5] = mysql.Arg(s.Country)
		}

		if s.Location.IsUnset() {
			vals[6] = mysql.Raw("DEFAULT")
		} else {
			vals[6] = mysql.Arg(s.Location)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FacilitySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("facilities")...)
}

func (s FacilitySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if !s.Address.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address")...),
			mysql.Arg(s.Address),
		}})
	}

	if !s.GoogleMapsLink.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "google_maps_link")...),
			mysql.Arg(s.GoogleMapsLink),
		}})
	}

	if !s.Website.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "website")...),
			mysql.Arg(s.Website),
		}})
	}

	if !s.Country.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "country")...),
			mysql.Arg(s.Country),
		}})
	}

	if !s.Location.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "location")...),
			mysql.Arg(s.Location),
		}})
	}

	return exprs
}

// FindFacility retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFacility(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Facility, error) {
	if len(cols) == 0 {
		return Facilities.Query(
			SelectWhere.Facilities.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Facilities.Query(
		SelectWhere.Facilities.ID.EQ(IDPK),
		sm.Columns(Facilities.Columns().Only(cols...)),
	).One(ctx, exec)
}

// FacilityExists checks the presence of a single record by primary key
func FacilityExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Facilities.Query(
		SelectWhere.Facilities.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Facility is retrieved from the database
func (o *Facility) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Facilities.AfterSelectHooks.RunHooks(ctx, exec, FacilitySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Facilities.AfterInsertHooks.RunHooks(ctx, exec, FacilitySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Facilities.AfterUpdateHooks.RunHooks(ctx, exec, FacilitySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Facilities.AfterDeleteHooks.RunHooks(ctx, exec, FacilitySlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the Facility
func (o *Facility) PrimaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Facility) pkEQ() dialect.Expression {
	return mysql.Quote("facilities", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Facility
func (o *Facility) Update(ctx context.Context, exec bob.Executor, s *FacilitySetter) error {
	_, err := Facilities.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Facility record with an executor
func (o *Facility) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Facilities.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Facility using the executor
func (o *Facility) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Facilities.Query(
		SelectWhere.Facilities.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after FacilitySlice is retrieved from the database
func (o FacilitySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Facilities.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Facilities.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Facilities.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Facilities.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FacilitySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("facilities", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FacilitySlice) copyMatchingRows(from ...*Facility) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FacilitySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Facilities.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Facility:
				o.copyMatchingRows(retrieved)
			case []*Facility:
				o.copyMatchingRows(retrieved...)
			case FacilitySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Facility or a slice of Facility
				// then run the AfterUpdateHooks on the slice
				_, err = Facilities.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FacilitySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Facilities.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Facility:
				o.copyMatchingRows(retrieved)
			case []*Facility:
				o.copyMatchingRows(retrieved...)
			case FacilitySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Facility or a slice of Facility
				// then run the AfterDeleteHooks on the slice
				_, err = Facilities.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FacilitySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FacilitySetter) error {
	_, err := Facilities.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o FacilitySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Facilities.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FacilitySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Facilities.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type facilityJoins[Q dialect.Joinable] struct {
	typ                   string
	LocationConfirmations func(context.Context) modAs[Q, confirmationColumns]
	CourtGroups           func(context.Context) modAs[Q, courtGroupColumns]
	Events                func(context.Context) modAs[Q, eventColumns]
	PartnerCards          func(context.Context) modAs[Q, partnerCardColumns]
	JoinRequests          func(context.Context) modAs[Q, joinRequestColumns]
}

func (j facilityJoins[Q]) aliasedAs(alias string) facilityJoins[Q] {
	return buildFacilityJoins[Q](buildFacilityColumns(alias), j.typ)
}

func buildFacilityJoins[Q dialect.Joinable](cols facilityColumns, typ string) facilityJoins[Q] {
	return facilityJoins[Q]{
		typ:                   typ,
		LocationConfirmations: facilitiesJoinLocationConfirmations[Q](cols, typ),
		CourtGroups:           facilitiesJoinCourtGroups[Q](cols, typ),
		Events:                facilitiesJoinEvents[Q](cols, typ),
		PartnerCards:          facilitiesJoinPartnerCards[Q](cols, typ),
		JoinRequests:          facilitiesJoinJoinRequests[Q](cols, typ),
	}
}

func facilitiesJoinLocationConfirmations[Q dialect.Joinable](from facilityColumns, typ string) func(context.Context) modAs[Q, confirmationColumns] {
	return func(ctx context.Context) modAs[Q, confirmationColumns] {
		return modAs[Q, confirmationColumns]{
			c: ConfirmationColumns,
			f: func(to confirmationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Confirmations.Name().As(to.Alias())).On(
						to.LocationID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

func facilitiesJoinCourtGroups[Q dialect.Joinable](from facilityColumns, typ string) func(context.Context) modAs[Q, courtGroupColumns] {
	return func(ctx context.Context) modAs[Q, courtGroupColumns] {
		return modAs[Q, courtGroupColumns]{
			c: CourtGroupColumns,
			f: func(to courtGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CourtGroups.Name().As(to.Alias())).On(
						to.FacilityID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

func facilitiesJoinEvents[Q dialect.Joinable](from facilityColumns, typ string) func(context.Context) modAs[Q, eventColumns] {
	return func(ctx context.Context) modAs[Q, eventColumns] {
		return modAs[Q, eventColumns]{
			c: EventColumns,
			f: func(to eventColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := EventLocationColumns.AliasedAs(EventLocationColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, EventLocations.Name().As(to.Alias())).On(
						to.LocationID.EQ(from.ID),
					))
				}
				{
					from := EventLocationColumns.AliasedAs(EventLocationColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, Events.Name().As(to.Alias())).On(
						to.ID.EQ(from.EventID),
					))
				}

				return mods
			},
		}
	}
}

func facilitiesJoinPartnerCards[Q dialect.Joinable](from facilityColumns, typ string) func(context.Context) modAs[Q, partnerCardColumns] {
	return func(ctx context.Context) modAs[Q, partnerCardColumns] {
		return modAs[Q, partnerCardColumns]{
			c: PartnerCardColumns,
			f: func(to partnerCardColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := FacilityPartnerCardColumns.AliasedAs(FacilityPartnerCardColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, FacilityPartnerCards.Name().As(to.Alias())).On(
						to.FacilityID.EQ(from.ID),
					))
				}
				{
					from := FacilityPartnerCardColumns.AliasedAs(FacilityPartnerCardColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, PartnerCards.Name().As(to.Alias())).On(
						to.ID.EQ(from.PartnerCardID),
					))
				}

				return mods
			},
		}
	}
}

func facilitiesJoinJoinRequests[Q dialect.Joinable](from facilityColumns, typ string) func(context.Context) modAs[Q, joinRequestColumns] {
	return func(ctx context.Context) modAs[Q, joinRequestColumns] {
		return modAs[Q, joinRequestColumns]{
			c: JoinRequestColumns,
			f: func(to joinRequestColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := JoinRequestLocationColumns.AliasedAs(JoinRequestLocationColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, JoinRequestLocations.Name().As(to.Alias())).On(
						to.LocationID.EQ(from.ID),
					))
				}
				{
					from := JoinRequestLocationColumns.AliasedAs(JoinRequestLocationColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, JoinRequests.Name().As(to.Alias())).On(
						to.ID.EQ(from.JoinRequestID),
					))
				}

				return mods
			},
		}
	}
}

// LocationConfirmations starts a query for related objects on confirmations
func (o *Facility) LocationConfirmations(mods ...bob.Mod[*dialect.SelectQuery]) ConfirmationsQuery {
	return Confirmations.Query(append(mods,
		sm.Where(ConfirmationColumns.LocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os FacilitySlice) LocationConfirmations(mods ...bob.Mod[*dialect.SelectQuery]) ConfirmationsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return Confirmations.Query(append(mods,
		sm.Where(mysql.Group(ConfirmationColumns.LocationID).In(PKArgs...)),
	)...)
}

// CourtGroups starts a query for related objects on court_groups
func (o *Facility) CourtGroups(mods ...bob.Mod[*dialect.SelectQuery]) CourtGroupsQuery {
	return CourtGroups.Query(append(mods,
		sm.Where(CourtGroupColumns.FacilityID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os FacilitySlice) CourtGroups(mods ...bob.Mod[*dialect.SelectQuery]) CourtGroupsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return CourtGroups.Query(append(mods,
		sm.Where(mysql.Group(CourtGroupColumns.FacilityID).In(PKArgs...)),
	)...)
}

// Events starts a query for related objects on events
func (o *Facility) Events(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	return Events.Query(append(mods,
		sm.InnerJoin(EventLocations.NameAs()).On(
			EventColumns.ID.EQ(EventLocationColumns.EventID)),
		sm.Where(EventLocationColumns.LocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os FacilitySlice) Events(mods ...bob.Mod[*dialect.SelectQuery]) EventsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return Events.Query(append(mods,
		sm.InnerJoin(EventLocations.NameAs()).On(
			EventColumns.ID.EQ(EventLocationColumns.EventID),
		),
		sm.Where(mysql.Group(EventLocationColumns.LocationID).In(PKArgs...)),
	)...)
}

// PartnerCards starts a query for related objects on partner_cards
func (o *Facility) PartnerCards(mods ...bob.Mod[*dialect.SelectQuery]) PartnerCardsQuery {
	return PartnerCards.Query(append(mods,
		sm.InnerJoin(FacilityPartnerCards.NameAs()).On(
			PartnerCardColumns.ID.EQ(FacilityPartnerCardColumns.PartnerCardID)),
		sm.Where(FacilityPartnerCardColumns.FacilityID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os FacilitySlice) PartnerCards(mods ...bob.Mod[*dialect.SelectQuery]) PartnerCardsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return PartnerCards.Query(append(mods,
		sm.InnerJoin(FacilityPartnerCards.NameAs()).On(
			PartnerCardColumns.ID.EQ(FacilityPartnerCardColumns.PartnerCardID),
		),
		sm.Where(mysql.Group(FacilityPartnerCardColumns.FacilityID).In(PKArgs...)),
	)...)
}

// JoinRequests starts a query for related objects on join_requests
func (o *Facility) JoinRequests(mods ...bob.Mod[*dialect.SelectQuery]) JoinRequestsQuery {
	return JoinRequests.Query(append(mods,
		sm.InnerJoin(JoinRequestLocations.NameAs()).On(
			JoinRequestColumns.ID.EQ(JoinRequestLocationColumns.JoinRequestID)),
		sm.Where(JoinRequestLocationColumns.LocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os FacilitySlice) JoinRequests(mods ...bob.Mod[*dialect.SelectQuery]) JoinRequestsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return JoinRequests.Query(append(mods,
		sm.InnerJoin(JoinRequestLocations.NameAs()).On(
			JoinRequestColumns.ID.EQ(JoinRequestLocationColumns.JoinRequestID),
		),
		sm.Where(mysql.Group(JoinRequestLocationColumns.LocationID).In(PKArgs...)),
	)...)
}

func (o *Facility) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "LocationConfirmations":
		rels, ok := retrieved.(ConfirmationSlice)
		if !ok {
			return fmt.Errorf("facility cannot load %T as %q", retrieved, name)
		}

		o.R.LocationConfirmations = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.LocationFacility = o
			}
		}
		return nil
	case "CourtGroups":
		rels, ok := retrieved.(CourtGroupSlice)
		if !ok {
			return fmt.Errorf("facility cannot load %T as %q", retrieved, name)
		}

		o.R.CourtGroups = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Facility = o
			}
		}
		return nil
	case "Events":
		rels, ok := retrieved.(EventSlice)
		if !ok {
			return fmt.Errorf("facility cannot load %T as %q", retrieved, name)
		}

		o.R.Events = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Facilities = FacilitySlice{o}
			}
		}
		return nil
	case "PartnerCards":
		rels, ok := retrieved.(PartnerCardSlice)
		if !ok {
			return fmt.Errorf("facility cannot load %T as %q", retrieved, name)
		}

		o.R.PartnerCards = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Facilities = FacilitySlice{o}
			}
		}
		return nil
	case "JoinRequests":
		rels, ok := retrieved.(JoinRequestSlice)
		if !ok {
			return fmt.Errorf("facility cannot load %T as %q", retrieved, name)
		}

		o.R.JoinRequests = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Facilities = FacilitySlice{o}
			}
		}
		return nil
	default:
		return fmt.Errorf("facility has no relationship %q", name)
	}
}

func ThenLoadFacilityLocationConfirmations(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityLocationConfirmations(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityLocationConfirmations", retrieved)
		}

		err := loader.LoadFacilityLocationConfirmations(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityLocationConfirmations loads the facility's LocationConfirmations into the .R struct
func (o *Facility) LoadFacilityLocationConfirmations(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.LocationConfirmations = nil

	related, err := o.LocationConfirmations(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.LocationFacility = o
	}

	o.R.LocationConfirmations = related
	return nil
}

// LoadFacilityLocationConfirmations loads the facility's LocationConfirmations into the .R struct
func (os FacilitySlice) LoadFacilityLocationConfirmations(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	confirmations, err := os.LocationConfirmations(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.LocationConfirmations = nil
	}

	for _, o := range os {
		for _, rel := range confirmations {
			if o.ID != rel.LocationID {
				continue
			}

			rel.R.LocationFacility = o

			o.R.LocationConfirmations = append(o.R.LocationConfirmations, rel)
		}
	}

	return nil
}

func ThenLoadFacilityCourtGroups(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityCourtGroups(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityCourtGroups", retrieved)
		}

		err := loader.LoadFacilityCourtGroups(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityCourtGroups loads the facility's CourtGroups into the .R struct
func (o *Facility) LoadFacilityCourtGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CourtGroups = nil

	related, err := o.CourtGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Facility = o
	}

	o.R.CourtGroups = related
	return nil
}

// LoadFacilityCourtGroups loads the facility's CourtGroups into the .R struct
func (os FacilitySlice) LoadFacilityCourtGroups(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	courtGroups, err := os.CourtGroups(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.CourtGroups = nil
	}

	for _, o := range os {
		for _, rel := range courtGroups {
			if o.ID != rel.FacilityID {
				continue
			}

			rel.R.Facility = o

			o.R.CourtGroups = append(o.R.CourtGroups, rel)
		}
	}

	return nil
}

func ThenLoadFacilityEvents(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityEvents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityEvents", retrieved)
		}

		err := loader.LoadFacilityEvents(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityEvents loads the facility's Events into the .R struct
func (o *Facility) LoadFacilityEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Events = nil

	related, err := o.Events(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Facilities = FacilitySlice{o}
	}

	o.R.Events = related
	return nil
}

// LoadFacilityEvents loads the facility's Events into the .R struct
func (os FacilitySlice) LoadFacilityEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(Events.Columns()))
	}

	q := os.Events(append(
		mods,
		sm.Columns(EventLocationColumns.LocationID.As("related_facilities.ID")),
	)...)

	IDSlice := []string{}

	mapper := scan.Mod(scan.StructMapper[*Event](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(string))
				row.ScheduleScan("related_facilities.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	events, err := bob.Allx[*Event, EventSlice](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Events = nil
	}

	for _, o := range os {
		for i, rel := range events {
			if o.ID != IDSlice[i] {
				continue
			}

			rel.R.Facilities = append(rel.R.Facilities, o)

			o.R.Events = append(o.R.Events, rel)
		}
	}

	return nil
}

func ThenLoadFacilityPartnerCards(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityPartnerCards(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityPartnerCards", retrieved)
		}

		err := loader.LoadFacilityPartnerCards(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityPartnerCards loads the facility's PartnerCards into the .R struct
func (o *Facility) LoadFacilityPartnerCards(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PartnerCards = nil

	related, err := o.PartnerCards(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Facilities = FacilitySlice{o}
	}

	o.R.PartnerCards = related
	return nil
}

// LoadFacilityPartnerCards loads the facility's PartnerCards into the .R struct
func (os FacilitySlice) LoadFacilityPartnerCards(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(PartnerCards.Columns()))
	}

	q := os.PartnerCards(append(
		mods,
		sm.Columns(FacilityPartnerCardColumns.FacilityID.As("related_facilities.ID")),
	)...)

	IDSlice := []string{}

	mapper := scan.Mod(scan.StructMapper[*PartnerCard](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(string))
				row.ScheduleScan("related_facilities.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	partnerCards, err := bob.Allx[*PartnerCard, PartnerCardSlice](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.PartnerCards = nil
	}

	for _, o := range os {
		for i, rel := range partnerCards {
			if o.ID != IDSlice[i] {
				continue
			}

			rel.R.Facilities = append(rel.R.Facilities, o)

			o.R.PartnerCards = append(o.R.PartnerCards, rel)
		}
	}

	return nil
}

func ThenLoadFacilityJoinRequests(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityJoinRequests(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityJoinRequests", retrieved)
		}

		err := loader.LoadFacilityJoinRequests(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityJoinRequests loads the facility's JoinRequests into the .R struct
func (o *Facility) LoadFacilityJoinRequests(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.JoinRequests = nil

	related, err := o.JoinRequests(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Facilities = FacilitySlice{o}
	}

	o.R.JoinRequests = related
	return nil
}

// LoadFacilityJoinRequests loads the facility's JoinRequests into the .R struct
func (os FacilitySlice) LoadFacilityJoinRequests(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(JoinRequests.Columns()))
	}

	q := os.JoinRequests(append(
		mods,
		sm.Columns(JoinRequestLocationColumns.LocationID.As("related_facilities.ID")),
	)...)

	IDSlice := []string{}

	mapper := scan.Mod(scan.StructMapper[*JoinRequest](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(string))
				row.ScheduleScan("related_facilities.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	joinRequests, err := bob.Allx[*JoinRequest, JoinRequestSlice](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.JoinRequests = nil
	}

	for _, o := range os {
		for i, rel := range joinRequests {
			if o.ID != IDSlice[i] {
				continue
			}

			rel.R.Facilities = append(rel.R.Facilities, o)

			o.R.JoinRequests = append(o.R.JoinRequests, rel)
		}
	}

	return nil
}

func insertFacilityLocationConfirmations0(ctx context.Context, exec bob.Executor, confirmations1 []*ConfirmationSetter, facility0 *Facility) (ConfirmationSlice, error) {
	for i := range confirmations1 {
		confirmations1[i].LocationID = omit.From(facility0.ID)
	}

	ret, err := Confirmations.Insert(bob.ToMods(confirmations1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertFacilityLocationConfirmations0: %w", err)
	}

	return ret, nil
}

func attachFacilityLocationConfirmations0(ctx context.Context, exec bob.Executor, count int, confirmations1 ConfirmationSlice, facility0 *Facility) (ConfirmationSlice, error) {
	setter := &ConfirmationSetter{
		LocationID: omit.From(facility0.ID),
	}

	err := confirmations1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityLocationConfirmations0: %w", err)
	}

	return confirmations1, nil
}

func (facility0 *Facility) InsertLocationConfirmations(ctx context.Context, exec bob.Executor, related ...*ConfirmationSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	confirmations1, err := insertFacilityLocationConfirmations0(ctx, exec, related, facility0)
	if err != nil {
		return err
	}

	facility0.R.LocationConfirmations = append(facility0.R.LocationConfirmations, confirmations1...)

	for _, rel := range confirmations1 {
		rel.R.LocationFacility = facility0
	}
	return nil
}

func (facility0 *Facility) AttachLocationConfirmations(ctx context.Context, exec bob.Executor, related ...*Confirmation) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	confirmations1 := ConfirmationSlice(related)

	_, err = attachFacilityLocationConfirmations0(ctx, exec, len(related), confirmations1, facility0)
	if err != nil {
		return err
	}

	facility0.R.LocationConfirmations = append(facility0.R.LocationConfirmations, confirmations1...)

	for _, rel := range related {
		rel.R.LocationFacility = facility0
	}

	return nil
}

func insertFacilityCourtGroups0(ctx context.Context, exec bob.Executor, courtGroups1 []*CourtGroupSetter, facility0 *Facility) (CourtGroupSlice, error) {
	for i := range courtGroups1 {
		courtGroups1[i].FacilityID = omit.From(facility0.ID)
	}

	ret, err := CourtGroups.Insert(bob.ToMods(courtGroups1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertFacilityCourtGroups0: %w", err)
	}

	return ret, nil
}

func attachFacilityCourtGroups0(ctx context.Context, exec bob.Executor, count int, courtGroups1 CourtGroupSlice, facility0 *Facility) (CourtGroupSlice, error) {
	setter := &CourtGroupSetter{
		FacilityID: omit.From(facility0.ID),
	}

	err := courtGroups1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityCourtGroups0: %w", err)
	}

	return courtGroups1, nil
}

func (facility0 *Facility) InsertCourtGroups(ctx context.Context, exec bob.Executor, related ...*CourtGroupSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	courtGroups1, err := insertFacilityCourtGroups0(ctx, exec, related, facility0)
	if err != nil {
		return err
	}

	facility0.R.CourtGroups = append(facility0.R.CourtGroups, courtGroups1...)

	for _, rel := range courtGroups1 {
		rel.R.Facility = facility0
	}
	return nil
}

func (facility0 *Facility) AttachCourtGroups(ctx context.Context, exec bob.Executor, related ...*CourtGroup) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	courtGroups1 := CourtGroupSlice(related)

	_, err = attachFacilityCourtGroups0(ctx, exec, len(related), courtGroups1, facility0)
	if err != nil {
		return err
	}

	facility0.R.CourtGroups = append(facility0.R.CourtGroups, courtGroups1...)

	for _, rel := range related {
		rel.R.Facility = facility0
	}

	return nil
}

func attachFacilityEvents0(ctx context.Context, exec bob.Executor, count int, facility0 *Facility, events2 EventSlice) (EventLocationSlice, error) {
	setters := make([]*EventLocationSetter, count)
	for i := 0; i < count; i++ {
		setters[i] = &EventLocationSetter{
			LocationID: omit.From(facility0.ID),
			EventID:    omit.From(events2[i].ID),
		}
	}

	eventLocations1, err := EventLocations.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityEvents0: %w", err)
	}

	return eventLocations1, nil
}

func (facility0 *Facility) InsertEvents(ctx context.Context, exec bob.Executor, related ...*EventSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := Events.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	events2 := EventSlice(inserted)

	_, err = attachFacilityEvents0(ctx, exec, len(related), facility0, events2)
	if err != nil {
		return err
	}

	facility0.R.Events = append(facility0.R.Events, events2...)

	for _, rel := range events2 {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}
	return nil
}

func (facility0 *Facility) AttachEvents(ctx context.Context, exec bob.Executor, related ...*Event) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	events2 := EventSlice(related)

	_, err = attachFacilityEvents0(ctx, exec, len(related), facility0, events2)
	if err != nil {
		return err
	}

	facility0.R.Events = append(facility0.R.Events, events2...)

	for _, rel := range related {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}

	return nil
}

func attachFacilityPartnerCards0(ctx context.Context, exec bob.Executor, count int, facility0 *Facility, partnerCards2 PartnerCardSlice) (FacilityPartnerCardSlice, error) {
	setters := make([]*FacilityPartnerCardSetter, count)
	for i := 0; i < count; i++ {
		setters[i] = &FacilityPartnerCardSetter{
			FacilityID:    omit.From(facility0.ID),
			PartnerCardID: omit.From(partnerCards2[i].ID),
		}
	}

	facilityPartnerCards1, err := FacilityPartnerCards.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityPartnerCards0: %w", err)
	}

	return facilityPartnerCards1, nil
}

func (facility0 *Facility) InsertPartnerCards(ctx context.Context, exec bob.Executor, related ...*PartnerCardSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := PartnerCards.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	partnerCards2 := PartnerCardSlice(inserted)

	_, err = attachFacilityPartnerCards0(ctx, exec, len(related), facility0, partnerCards2)
	if err != nil {
		return err
	}

	facility0.R.PartnerCards = append(facility0.R.PartnerCards, partnerCards2...)

	for _, rel := range partnerCards2 {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}
	return nil
}

func (facility0 *Facility) AttachPartnerCards(ctx context.Context, exec bob.Executor, related ...*PartnerCard) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	partnerCards2 := PartnerCardSlice(related)

	_, err = attachFacilityPartnerCards0(ctx, exec, len(related), facility0, partnerCards2)
	if err != nil {
		return err
	}

	facility0.R.PartnerCards = append(facility0.R.PartnerCards, partnerCards2...)

	for _, rel := range related {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}

	return nil
}

func attachFacilityJoinRequests0(ctx context.Context, exec bob.Executor, count int, facility0 *Facility, joinRequests2 JoinRequestSlice) (JoinRequestLocationSlice, error) {
	setters := make([]*JoinRequestLocationSetter, count)
	for i := 0; i < count; i++ {
		setters[i] = &JoinRequestLocationSetter{
			LocationID:    omit.From(facility0.ID),
			JoinRequestID: omit.From(joinRequests2[i].ID),
		}
	}

	joinRequestLocations1, err := JoinRequestLocations.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityJoinRequests0: %w", err)
	}

	return joinRequestLocations1, nil
}

func (facility0 *Facility) InsertJoinRequests(ctx context.Context, exec bob.Executor, related ...*JoinRequestSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := JoinRequests.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	joinRequests2 := JoinRequestSlice(inserted)

	_, err = attachFacilityJoinRequests0(ctx, exec, len(related), facility0, joinRequests2)
	if err != nil {
		return err
	}

	facility0.R.JoinRequests = append(facility0.R.JoinRequests, joinRequests2...)

	for _, rel := range joinRequests2 {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}
	return nil
}

func (facility0 *Facility) AttachJoinRequests(ctx context.Context, exec bob.Executor, related ...*JoinRequest) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	joinRequests2 := JoinRequestSlice(related)

	_, err = attachFacilityJoinRequests0(ctx, exec, len(related), facility0, joinRequests2)
	if err != nil {
		return err
	}

	facility0.R.JoinRequests = append(facility0.R.JoinRequests, joinRequests2...)

	for _, rel := range related {
		rel.R.Facilities = append(rel.R.Facilities, facility0)
	}

	return nil
}
