// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// FacilityPartnerCard is an object representing the database table.
type FacilityPartnerCard struct {
	FacilityID    string `db:"facility_id,pk" `
	PartnerCardID string `db:"partner_card_id,pk" `

	R facilityPartnerCardR `db:"-" `
}

// FacilityPartnerCardSlice is an alias for a slice of pointers to FacilityPartnerCard.
// This should almost always be used instead of []*FacilityPartnerCard.
type FacilityPartnerCardSlice []*FacilityPartnerCard

// FacilityPartnerCards contains methods to work with the facility_partner_cards table
var FacilityPartnerCards = mysql.NewTablex[*FacilityPartnerCard, FacilityPartnerCardSlice, *FacilityPartnerCardSetter]("facility_partner_cards", []string{"facility_id", "partner_card_id"})

// FacilityPartnerCardsQuery is a query on the facility_partner_cards table
type FacilityPartnerCardsQuery = *mysql.ViewQuery[*FacilityPartnerCard, FacilityPartnerCardSlice]

// facilityPartnerCardR is where relationships are stored.
type facilityPartnerCardR struct {
	Facility    *Facility    // facility_partner_cards_ibfk_1
	PartnerCard *PartnerCard // facility_partner_cards_ibfk_2
}

type facilityPartnerCardColumnNames struct {
	FacilityID    string
	PartnerCardID string
}

var FacilityPartnerCardColumns = buildFacilityPartnerCardColumns("facility_partner_cards")

type facilityPartnerCardColumns struct {
	tableAlias    string
	FacilityID    mysql.Expression
	PartnerCardID mysql.Expression
}

func (c facilityPartnerCardColumns) Alias() string {
	return c.tableAlias
}

func (facilityPartnerCardColumns) AliasedAs(alias string) facilityPartnerCardColumns {
	return buildFacilityPartnerCardColumns(alias)
}

func buildFacilityPartnerCardColumns(alias string) facilityPartnerCardColumns {
	return facilityPartnerCardColumns{
		tableAlias:    alias,
		FacilityID:    mysql.Quote(alias, "facility_id"),
		PartnerCardID: mysql.Quote(alias, "partner_card_id"),
	}
}

type facilityPartnerCardWhere[Q mysql.Filterable] struct {
	FacilityID    mysql.WhereMod[Q, string]
	PartnerCardID mysql.WhereMod[Q, string]
}

func (facilityPartnerCardWhere[Q]) AliasedAs(alias string) facilityPartnerCardWhere[Q] {
	return buildFacilityPartnerCardWhere[Q](buildFacilityPartnerCardColumns(alias))
}

func buildFacilityPartnerCardWhere[Q mysql.Filterable](cols facilityPartnerCardColumns) facilityPartnerCardWhere[Q] {
	return facilityPartnerCardWhere[Q]{
		FacilityID:    mysql.Where[Q, string](cols.FacilityID),
		PartnerCardID: mysql.Where[Q, string](cols.PartnerCardID),
	}
}

var FacilityPartnerCardErrors = &facilityPartnerCardErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type facilityPartnerCardErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// FacilityPartnerCardSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type FacilityPartnerCardSetter struct {
	FacilityID    omit.Val[string] `db:"facility_id,pk" `
	PartnerCardID omit.Val[string] `db:"partner_card_id,pk" `
}

func (s FacilityPartnerCardSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if !s.FacilityID.IsUnset() {
		vals = append(vals, "facility_id")
	}

	if !s.PartnerCardID.IsUnset() {
		vals = append(vals, "partner_card_id")
	}

	return vals
}

func (s FacilityPartnerCardSetter) Overwrite(t *FacilityPartnerCard) {
	if !s.FacilityID.IsUnset() {
		t.FacilityID, _ = s.FacilityID.Get()
	}
	if !s.PartnerCardID.IsUnset() {
		t.PartnerCardID, _ = s.PartnerCardID.Get()
	}
}

func (s *FacilityPartnerCardSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return FacilityPartnerCards.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.FacilityID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.FacilityID)
		}

		if s.PartnerCardID.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.PartnerCardID)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s FacilityPartnerCardSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("facility_partner_cards")...)
}

func (s FacilityPartnerCardSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if !s.FacilityID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "facility_id")...),
			mysql.Arg(s.FacilityID),
		}})
	}

	if !s.PartnerCardID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "partner_card_id")...),
			mysql.Arg(s.PartnerCardID),
		}})
	}

	return exprs
}

// FindFacilityPartnerCard retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindFacilityPartnerCard(ctx context.Context, exec bob.Executor, FacilityIDPK string, PartnerCardIDPK string, cols ...string) (*FacilityPartnerCard, error) {
	if len(cols) == 0 {
		return FacilityPartnerCards.Query(
			SelectWhere.FacilityPartnerCards.FacilityID.EQ(FacilityIDPK),
			SelectWhere.FacilityPartnerCards.PartnerCardID.EQ(PartnerCardIDPK),
		).One(ctx, exec)
	}

	return FacilityPartnerCards.Query(
		SelectWhere.FacilityPartnerCards.FacilityID.EQ(FacilityIDPK),
		SelectWhere.FacilityPartnerCards.PartnerCardID.EQ(PartnerCardIDPK),
		sm.Columns(FacilityPartnerCards.Columns().Only(cols...)),
	).One(ctx, exec)
}

// FacilityPartnerCardExists checks the presence of a single record by primary key
func FacilityPartnerCardExists(ctx context.Context, exec bob.Executor, FacilityIDPK string, PartnerCardIDPK string) (bool, error) {
	return FacilityPartnerCards.Query(
		SelectWhere.FacilityPartnerCards.FacilityID.EQ(FacilityIDPK),
		SelectWhere.FacilityPartnerCards.PartnerCardID.EQ(PartnerCardIDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after FacilityPartnerCard is retrieved from the database
func (o *FacilityPartnerCard) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FacilityPartnerCards.AfterSelectHooks.RunHooks(ctx, exec, FacilityPartnerCardSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = FacilityPartnerCards.AfterInsertHooks.RunHooks(ctx, exec, FacilityPartnerCardSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = FacilityPartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, FacilityPartnerCardSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = FacilityPartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, FacilityPartnerCardSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the FacilityPartnerCard
func (o *FacilityPartnerCard) PrimaryKeyVals() bob.Expression {
	return mysql.ArgGroup(
		o.FacilityID,
		o.PartnerCardID,
	)
}

func (o *FacilityPartnerCard) pkEQ() dialect.Expression {
	return mysql.Group(mysql.Quote("facility_partner_cards", "facility_id"), mysql.Quote("facility_partner_cards", "partner_card_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the FacilityPartnerCard
func (o *FacilityPartnerCard) Update(ctx context.Context, exec bob.Executor, s *FacilityPartnerCardSetter) error {
	_, err := FacilityPartnerCards.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single FacilityPartnerCard record with an executor
func (o *FacilityPartnerCard) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := FacilityPartnerCards.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the FacilityPartnerCard using the executor
func (o *FacilityPartnerCard) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := FacilityPartnerCards.Query(
		SelectWhere.FacilityPartnerCards.FacilityID.EQ(o.FacilityID),
		SelectWhere.FacilityPartnerCards.PartnerCardID.EQ(o.PartnerCardID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after FacilityPartnerCardSlice is retrieved from the database
func (o FacilityPartnerCardSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = FacilityPartnerCards.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = FacilityPartnerCards.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = FacilityPartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = FacilityPartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o FacilityPartnerCardSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Group(mysql.Quote("facility_partner_cards", "facility_id"), mysql.Quote("facility_partner_cards", "partner_card_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o FacilityPartnerCardSlice) copyMatchingRows(from ...*FacilityPartnerCard) {
	for i, old := range o {
		for _, new := range from {
			if new.FacilityID != old.FacilityID {
				continue
			}
			if new.PartnerCardID != old.PartnerCardID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o FacilityPartnerCardSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FacilityPartnerCards.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FacilityPartnerCard:
				o.copyMatchingRows(retrieved)
			case []*FacilityPartnerCard:
				o.copyMatchingRows(retrieved...)
			case FacilityPartnerCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FacilityPartnerCard or a slice of FacilityPartnerCard
				// then run the AfterUpdateHooks on the slice
				_, err = FacilityPartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o FacilityPartnerCardSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return FacilityPartnerCards.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *FacilityPartnerCard:
				o.copyMatchingRows(retrieved)
			case []*FacilityPartnerCard:
				o.copyMatchingRows(retrieved...)
			case FacilityPartnerCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a FacilityPartnerCard or a slice of FacilityPartnerCard
				// then run the AfterDeleteHooks on the slice
				_, err = FacilityPartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o FacilityPartnerCardSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals FacilityPartnerCardSetter) error {
	_, err := FacilityPartnerCards.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o FacilityPartnerCardSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := FacilityPartnerCards.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o FacilityPartnerCardSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := FacilityPartnerCards.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type facilityPartnerCardJoins[Q dialect.Joinable] struct {
	typ         string
	Facility    func(context.Context) modAs[Q, facilityColumns]
	PartnerCard func(context.Context) modAs[Q, partnerCardColumns]
}

func (j facilityPartnerCardJoins[Q]) aliasedAs(alias string) facilityPartnerCardJoins[Q] {
	return buildFacilityPartnerCardJoins[Q](buildFacilityPartnerCardColumns(alias), j.typ)
}

func buildFacilityPartnerCardJoins[Q dialect.Joinable](cols facilityPartnerCardColumns, typ string) facilityPartnerCardJoins[Q] {
	return facilityPartnerCardJoins[Q]{
		typ:         typ,
		Facility:    facilityPartnerCardsJoinFacility[Q](cols, typ),
		PartnerCard: facilityPartnerCardsJoinPartnerCard[Q](cols, typ),
	}
}

func facilityPartnerCardsJoinFacility[Q dialect.Joinable](from facilityPartnerCardColumns, typ string) func(context.Context) modAs[Q, facilityColumns] {
	return func(ctx context.Context) modAs[Q, facilityColumns] {
		return modAs[Q, facilityColumns]{
			c: FacilityColumns,
			f: func(to facilityColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Facilities.Name().As(to.Alias())).On(
						to.ID.EQ(from.FacilityID),
					))
				}

				return mods
			},
		}
	}
}

func facilityPartnerCardsJoinPartnerCard[Q dialect.Joinable](from facilityPartnerCardColumns, typ string) func(context.Context) modAs[Q, partnerCardColumns] {
	return func(ctx context.Context) modAs[Q, partnerCardColumns] {
		return modAs[Q, partnerCardColumns]{
			c: PartnerCardColumns,
			f: func(to partnerCardColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PartnerCards.Name().As(to.Alias())).On(
						to.ID.EQ(from.PartnerCardID),
					))
				}

				return mods
			},
		}
	}
}

// Facility starts a query for related objects on facilities
func (o *FacilityPartnerCard) Facility(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	return Facilities.Query(append(mods,
		sm.Where(FacilityColumns.ID.EQ(mysql.Arg(o.FacilityID))),
	)...)
}

func (os FacilityPartnerCardSlice) Facility(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.FacilityID)
	}

	return Facilities.Query(append(mods,
		sm.Where(mysql.Group(FacilityColumns.ID).In(PKArgs...)),
	)...)
}

// PartnerCard starts a query for related objects on partner_cards
func (o *FacilityPartnerCard) PartnerCard(mods ...bob.Mod[*dialect.SelectQuery]) PartnerCardsQuery {
	return PartnerCards.Query(append(mods,
		sm.Where(PartnerCardColumns.ID.EQ(mysql.Arg(o.PartnerCardID))),
	)...)
}

func (os FacilityPartnerCardSlice) PartnerCard(mods ...bob.Mod[*dialect.SelectQuery]) PartnerCardsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.PartnerCardID)
	}

	return PartnerCards.Query(append(mods,
		sm.Where(mysql.Group(PartnerCardColumns.ID).In(PKArgs...)),
	)...)
}

func (o *FacilityPartnerCard) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Facility":
		rel, ok := retrieved.(*Facility)
		if !ok {
			return fmt.Errorf("facilityPartnerCard cannot load %T as %q", retrieved, name)
		}

		o.R.Facility = rel

		return nil
	case "PartnerCard":
		rel, ok := retrieved.(*PartnerCard)
		if !ok {
			return fmt.Errorf("facilityPartnerCard cannot load %T as %q", retrieved, name)
		}

		o.R.PartnerCard = rel

		return nil
	default:
		return fmt.Errorf("facilityPartnerCard has no relationship %q", name)
	}
}

func PreloadFacilityPartnerCardFacility(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*Facility, FacilitySlice](orm.Relationship{
		Name: "Facility",
		Sides: []orm.RelSide{
			{
				From: TableNames.FacilityPartnerCards,
				To:   TableNames.Facilities,
				FromColumns: []string{
					ColumnNames.FacilityPartnerCards.FacilityID,
				},
				ToColumns: []string{
					ColumnNames.Facilities.ID,
				},
			},
		},
	}, Facilities.Columns().Names(), opts...)
}

func ThenLoadFacilityPartnerCardFacility(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityPartnerCardFacility(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityPartnerCardFacility", retrieved)
		}

		err := loader.LoadFacilityPartnerCardFacility(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityPartnerCardFacility loads the facilityPartnerCard's Facility into the .R struct
func (o *FacilityPartnerCard) LoadFacilityPartnerCardFacility(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Facility = nil

	related, err := o.Facility(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Facility = related
	return nil
}

// LoadFacilityPartnerCardFacility loads the facilityPartnerCard's Facility into the .R struct
func (os FacilityPartnerCardSlice) LoadFacilityPartnerCardFacility(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	facilities, err := os.Facility(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range facilities {
			if o.FacilityID != rel.ID {
				continue
			}

			o.R.Facility = rel
			break
		}
	}

	return nil
}

func PreloadFacilityPartnerCardPartnerCard(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*PartnerCard, PartnerCardSlice](orm.Relationship{
		Name: "PartnerCard",
		Sides: []orm.RelSide{
			{
				From: TableNames.FacilityPartnerCards,
				To:   TableNames.PartnerCards,
				FromColumns: []string{
					ColumnNames.FacilityPartnerCards.PartnerCardID,
				},
				ToColumns: []string{
					ColumnNames.PartnerCards.ID,
				},
			},
		},
	}, PartnerCards.Columns().Names(), opts...)
}

func ThenLoadFacilityPartnerCardPartnerCard(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadFacilityPartnerCardPartnerCard(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load FacilityPartnerCardPartnerCard", retrieved)
		}

		err := loader.LoadFacilityPartnerCardPartnerCard(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadFacilityPartnerCardPartnerCard loads the facilityPartnerCard's PartnerCard into the .R struct
func (o *FacilityPartnerCard) LoadFacilityPartnerCardPartnerCard(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PartnerCard = nil

	related, err := o.PartnerCard(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.PartnerCard = related
	return nil
}

// LoadFacilityPartnerCardPartnerCard loads the facilityPartnerCard's PartnerCard into the .R struct
func (os FacilityPartnerCardSlice) LoadFacilityPartnerCardPartnerCard(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	partnerCards, err := os.PartnerCard(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range partnerCards {
			if o.PartnerCardID != rel.ID {
				continue
			}

			o.R.PartnerCard = rel
			break
		}
	}

	return nil
}

func attachFacilityPartnerCardFacility0(ctx context.Context, exec bob.Executor, count int, facilityPartnerCard0 *FacilityPartnerCard, facility1 *Facility) (*FacilityPartnerCard, error) {
	setter := &FacilityPartnerCardSetter{
		FacilityID: omit.From(facility1.ID),
	}

	err := facilityPartnerCard0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityPartnerCardFacility0: %w", err)
	}

	return facilityPartnerCard0, nil
}

func (facilityPartnerCard0 *FacilityPartnerCard) InsertFacility(ctx context.Context, exec bob.Executor, related *FacilitySetter) error {
	facility1, err := Facilities.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachFacilityPartnerCardFacility0(ctx, exec, 1, facilityPartnerCard0, facility1)
	if err != nil {
		return err
	}

	facilityPartnerCard0.R.Facility = facility1

	return nil
}

func (facilityPartnerCard0 *FacilityPartnerCard) AttachFacility(ctx context.Context, exec bob.Executor, facility1 *Facility) error {
	var err error

	_, err = attachFacilityPartnerCardFacility0(ctx, exec, 1, facilityPartnerCard0, facility1)
	if err != nil {
		return err
	}

	facilityPartnerCard0.R.Facility = facility1

	return nil
}

func attachFacilityPartnerCardPartnerCard0(ctx context.Context, exec bob.Executor, count int, facilityPartnerCard0 *FacilityPartnerCard, partnerCard1 *PartnerCard) (*FacilityPartnerCard, error) {
	setter := &FacilityPartnerCardSetter{
		PartnerCardID: omit.From(partnerCard1.ID),
	}

	err := facilityPartnerCard0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachFacilityPartnerCardPartnerCard0: %w", err)
	}

	return facilityPartnerCard0, nil
}

func (facilityPartnerCard0 *FacilityPartnerCard) InsertPartnerCard(ctx context.Context, exec bob.Executor, related *PartnerCardSetter) error {
	partnerCard1, err := PartnerCards.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachFacilityPartnerCardPartnerCard0(ctx, exec, 1, facilityPartnerCard0, partnerCard1)
	if err != nil {
		return err
	}

	facilityPartnerCard0.R.PartnerCard = partnerCard1

	return nil
}

func (facilityPartnerCard0 *FacilityPartnerCard) AttachPartnerCard(ctx context.Context, exec bob.Executor, partnerCard1 *PartnerCard) error {
	var err error

	_, err = attachFacilityPartnerCardPartnerCard0(ctx, exec, 1, facilityPartnerCard0, partnerCard1)
	if err != nil {
		return err
	}

	facilityPartnerCard0.R.PartnerCard = partnerCard1

	return nil
}
