// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"strconv"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/scan"
)

// PartnerCard is an object representing the database table.
type PartnerCard struct {
	ID   string `db:"id,pk" `
	Name string `db:"name" `

	R partnerCardR `db:"-" `
}

// PartnerCardSlice is an alias for a slice of pointers to PartnerCard.
// This should almost always be used instead of []*PartnerCard.
type PartnerCardSlice []*PartnerCard

// PartnerCards contains methods to work with the partner_cards table
var PartnerCards = mysql.NewTablex[*PartnerCard, PartnerCardSlice, *PartnerCardSetter]("partner_cards", []string{"id"})

// PartnerCardsQuery is a query on the partner_cards table
type PartnerCardsQuery = *mysql.ViewQuery[*PartnerCard, PartnerCardSlice]

// partnerCardR is where relationships are stored.
type partnerCardR struct {
	Facilities FacilitySlice // facility_partner_cards_ibfk_1facility_partner_cards_ibfk_2
}

type partnerCardColumnNames struct {
	ID   string
	Name string
}

var PartnerCardColumns = buildPartnerCardColumns("partner_cards")

type partnerCardColumns struct {
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
}

func (c partnerCardColumns) Alias() string {
	return c.tableAlias
}

func (partnerCardColumns) AliasedAs(alias string) partnerCardColumns {
	return buildPartnerCardColumns(alias)
}

func buildPartnerCardColumns(alias string) partnerCardColumns {
	return partnerCardColumns{
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
	}
}

type partnerCardWhere[Q mysql.Filterable] struct {
	ID   mysql.WhereMod[Q, string]
	Name mysql.WhereMod[Q, string]
}

func (partnerCardWhere[Q]) AliasedAs(alias string) partnerCardWhere[Q] {
	return buildPartnerCardWhere[Q](buildPartnerCardColumns(alias))
}

func buildPartnerCardWhere[Q mysql.Filterable](cols partnerCardColumns) partnerCardWhere[Q] {
	return partnerCardWhere[Q]{
		ID:   mysql.Where[Q, string](cols.ID),
		Name: mysql.Where[Q, string](cols.Name),
	}
}

var PartnerCardErrors = &partnerCardErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type partnerCardErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// PartnerCardSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PartnerCardSetter struct {
	ID   omit.Val[string] `db:"id,pk" `
	Name omit.Val[string] `db:"name" `
}

func (s PartnerCardSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}

	return vals
}

func (s PartnerCardSetter) Overwrite(t *PartnerCard) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.Name.IsUnset() {
		t.Name, _ = s.Name.Get()
	}
}

func (s *PartnerCardSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PartnerCards.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.ID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.ID)
		}

		if s.Name.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.Name)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PartnerCardSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("partner_cards")...)
}

func (s PartnerCardSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	return exprs
}

// FindPartnerCard retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPartnerCard(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*PartnerCard, error) {
	if len(cols) == 0 {
		return PartnerCards.Query(
			SelectWhere.PartnerCards.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return PartnerCards.Query(
		SelectWhere.PartnerCards.ID.EQ(IDPK),
		sm.Columns(PartnerCards.Columns().Only(cols...)),
	).One(ctx, exec)
}

// PartnerCardExists checks the presence of a single record by primary key
func PartnerCardExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return PartnerCards.Query(
		SelectWhere.PartnerCards.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PartnerCard is retrieved from the database
func (o *PartnerCard) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PartnerCards.AfterSelectHooks.RunHooks(ctx, exec, PartnerCardSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PartnerCards.AfterInsertHooks.RunHooks(ctx, exec, PartnerCardSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, PartnerCardSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, PartnerCardSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the PartnerCard
func (o *PartnerCard) PrimaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *PartnerCard) pkEQ() dialect.Expression {
	return mysql.Quote("partner_cards", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PartnerCard
func (o *PartnerCard) Update(ctx context.Context, exec bob.Executor, s *PartnerCardSetter) error {
	_, err := PartnerCards.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single PartnerCard record with an executor
func (o *PartnerCard) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PartnerCards.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PartnerCard using the executor
func (o *PartnerCard) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PartnerCards.Query(
		SelectWhere.PartnerCards.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PartnerCardSlice is retrieved from the database
func (o PartnerCardSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PartnerCards.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PartnerCards.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PartnerCardSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("partner_cards", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PartnerCardSlice) copyMatchingRows(from ...*PartnerCard) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PartnerCardSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PartnerCards.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PartnerCard:
				o.copyMatchingRows(retrieved)
			case []*PartnerCard:
				o.copyMatchingRows(retrieved...)
			case PartnerCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PartnerCard or a slice of PartnerCard
				// then run the AfterUpdateHooks on the slice
				_, err = PartnerCards.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PartnerCardSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PartnerCards.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PartnerCard:
				o.copyMatchingRows(retrieved)
			case []*PartnerCard:
				o.copyMatchingRows(retrieved...)
			case PartnerCardSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PartnerCard or a slice of PartnerCard
				// then run the AfterDeleteHooks on the slice
				_, err = PartnerCards.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PartnerCardSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PartnerCardSetter) error {
	_, err := PartnerCards.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o PartnerCardSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PartnerCards.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PartnerCardSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PartnerCards.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type partnerCardJoins[Q dialect.Joinable] struct {
	typ        string
	Facilities func(context.Context) modAs[Q, facilityColumns]
}

func (j partnerCardJoins[Q]) aliasedAs(alias string) partnerCardJoins[Q] {
	return buildPartnerCardJoins[Q](buildPartnerCardColumns(alias), j.typ)
}

func buildPartnerCardJoins[Q dialect.Joinable](cols partnerCardColumns, typ string) partnerCardJoins[Q] {
	return partnerCardJoins[Q]{
		typ:        typ,
		Facilities: partnerCardsJoinFacilities[Q](cols, typ),
	}
}

func partnerCardsJoinFacilities[Q dialect.Joinable](from partnerCardColumns, typ string) func(context.Context) modAs[Q, facilityColumns] {
	return func(ctx context.Context) modAs[Q, facilityColumns] {
		return modAs[Q, facilityColumns]{
			c: FacilityColumns,
			f: func(to facilityColumns) bob.Mod[Q] {
				random := strconv.FormatInt(randInt(), 10)
				mods := make(mods.QueryMods[Q], 0, 2)

				{
					to := FacilityPartnerCardColumns.AliasedAs(FacilityPartnerCardColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, FacilityPartnerCards.Name().As(to.Alias())).On(
						to.PartnerCardID.EQ(from.ID),
					))
				}
				{
					from := FacilityPartnerCardColumns.AliasedAs(FacilityPartnerCardColumns.Alias() + random)
					mods = append(mods, dialect.Join[Q](typ, Facilities.Name().As(to.Alias())).On(
						to.ID.EQ(from.FacilityID),
					))
				}

				return mods
			},
		}
	}
}

// Facilities starts a query for related objects on facilities
func (o *PartnerCard) Facilities(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	return Facilities.Query(append(mods,
		sm.InnerJoin(FacilityPartnerCards.NameAs()).On(
			FacilityColumns.ID.EQ(FacilityPartnerCardColumns.FacilityID)),
		sm.Where(FacilityPartnerCardColumns.PartnerCardID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os PartnerCardSlice) Facilities(mods ...bob.Mod[*dialect.SelectQuery]) FacilitiesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return Facilities.Query(append(mods,
		sm.InnerJoin(FacilityPartnerCards.NameAs()).On(
			FacilityColumns.ID.EQ(FacilityPartnerCardColumns.FacilityID),
		),
		sm.Where(mysql.Group(FacilityPartnerCardColumns.PartnerCardID).In(PKArgs...)),
	)...)
}

func (o *PartnerCard) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Facilities":
		rels, ok := retrieved.(FacilitySlice)
		if !ok {
			return fmt.Errorf("partnerCard cannot load %T as %q", retrieved, name)
		}

		o.R.Facilities = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.PartnerCards = PartnerCardSlice{o}
			}
		}
		return nil
	default:
		return fmt.Errorf("partnerCard has no relationship %q", name)
	}
}

func ThenLoadPartnerCardFacilities(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPartnerCardFacilities(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PartnerCardFacilities", retrieved)
		}

		err := loader.LoadPartnerCardFacilities(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPartnerCardFacilities loads the partnerCard's Facilities into the .R struct
func (o *PartnerCard) LoadPartnerCardFacilities(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Facilities = nil

	related, err := o.Facilities(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PartnerCards = PartnerCardSlice{o}
	}

	o.R.Facilities = related
	return nil
}

// LoadPartnerCardFacilities loads the partnerCard's Facilities into the .R struct
func (os PartnerCardSlice) LoadPartnerCardFacilities(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// since we are changing the columns, we need to check if the original columns were set or add the defaults
	sq := dialect.SelectQuery{}
	for _, mod := range mods {
		mod.Apply(&sq)
	}

	if len(sq.SelectList.Columns) == 0 {
		mods = append(mods, sm.Columns(Facilities.Columns()))
	}

	q := os.Facilities(append(
		mods,
		sm.Columns(FacilityPartnerCardColumns.PartnerCardID.As("related_partner_cards.ID")),
	)...)

	IDSlice := []string{}

	mapper := scan.Mod(scan.StructMapper[*Facility](), func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any, any) error) {
		return func(row *scan.Row) (any, error) {
				IDSlice = append(IDSlice, *new(string))
				row.ScheduleScan("related_partner_cards.ID", &IDSlice[len(IDSlice)-1])

				return nil, nil
			},
			func(any, any) error {
				return nil
			}
	})

	facilities, err := bob.Allx[*Facility, FacilitySlice](ctx, exec, q, mapper)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Facilities = nil
	}

	for _, o := range os {
		for i, rel := range facilities {
			if o.ID != IDSlice[i] {
				continue
			}

			rel.R.PartnerCards = append(rel.R.PartnerCards, o)

			o.R.Facilities = append(o.R.Facilities, rel)
		}
	}

	return nil
}

func attachPartnerCardFacilities0(ctx context.Context, exec bob.Executor, count int, partnerCard0 *PartnerCard, facilities2 FacilitySlice) (FacilityPartnerCardSlice, error) {
	setters := make([]*FacilityPartnerCardSetter, count)
	for i := 0; i < count; i++ {
		setters[i] = &FacilityPartnerCardSetter{
			PartnerCardID: omit.From(partnerCard0.ID),
			FacilityID:    omit.From(facilities2[i].ID),
		}
	}

	facilityPartnerCards1, err := FacilityPartnerCards.Insert(bob.ToMods(setters...)).All(ctx, exec)
	if err != nil {
		return nil, fmt.Errorf("attachPartnerCardFacilities0: %w", err)
	}

	return facilityPartnerCards1, nil
}

func (partnerCard0 *PartnerCard) InsertFacilities(ctx context.Context, exec bob.Executor, related ...*FacilitySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inserted, err := Facilities.Insert(bob.ToMods(related...)).All(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}
	facilities2 := FacilitySlice(inserted)

	_, err = attachPartnerCardFacilities0(ctx, exec, len(related), partnerCard0, facilities2)
	if err != nil {
		return err
	}

	partnerCard0.R.Facilities = append(partnerCard0.R.Facilities, facilities2...)

	for _, rel := range facilities2 {
		rel.R.PartnerCards = append(rel.R.PartnerCards, partnerCard0)
	}
	return nil
}

func (partnerCard0 *PartnerCard) AttachFacilities(ctx context.Context, exec bob.Executor, related ...*Facility) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	facilities2 := FacilitySlice(related)

	_, err = attachPartnerCardFacilities0(ctx, exec, len(related), partnerCard0, facilities2)
	if err != nil {
		return err
	}

	partnerCard0.R.Facilities = append(partnerCard0.R.Facilities, facilities2...)

	for _, rel := range related {
		rel.R.PartnerCards = append(rel.R.PartnerCards, partnerCard0)
	}

	return nil
}
