// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// PricePeriod is an object representing the database table.
type PricePeriod struct {
	ID           int32     `db:"id,pk,autoincr" `
	CourtGroupID int32     `db:"court_group_id" `
	ValidFrom    time.Time `db:"valid_from" `
	ValidTo      time.Time `db:"valid_to" `

	R pricePeriodR `db:"-" `
}

// PricePeriodSlice is an alias for a slice of pointers to PricePeriod.
// This should almost always be used instead of []*PricePeriod.
type PricePeriodSlice []*PricePeriod

// PricePeriods contains methods to work with the price_periods table
var PricePeriods = mysql.NewTablex[*PricePeriod, PricePeriodSlice, *PricePeriodSetter]("price_periods", []string{"id"})

// PricePeriodsQuery is a query on the price_periods table
type PricePeriodsQuery = *mysql.ViewQuery[*PricePeriod, PricePeriodSlice]

// pricePeriodR is where relationships are stored.
type pricePeriodR struct {
	CourtGroup *CourtGroup    // price_periods_ibfk_1
	PriceRules PriceRuleSlice // price_rules_ibfk_1
}

type pricePeriodColumnNames struct {
	ID           string
	CourtGroupID string
	ValidFrom    string
	ValidTo      string
}

var PricePeriodColumns = buildPricePeriodColumns("price_periods")

type pricePeriodColumns struct {
	tableAlias   string
	ID           mysql.Expression
	CourtGroupID mysql.Expression
	ValidFrom    mysql.Expression
	ValidTo      mysql.Expression
}

func (c pricePeriodColumns) Alias() string {
	return c.tableAlias
}

func (pricePeriodColumns) AliasedAs(alias string) pricePeriodColumns {
	return buildPricePeriodColumns(alias)
}

func buildPricePeriodColumns(alias string) pricePeriodColumns {
	return pricePeriodColumns{
		tableAlias:   alias,
		ID:           mysql.Quote(alias, "id"),
		CourtGroupID: mysql.Quote(alias, "court_group_id"),
		ValidFrom:    mysql.Quote(alias, "valid_from"),
		ValidTo:      mysql.Quote(alias, "valid_to"),
	}
}

type pricePeriodWhere[Q mysql.Filterable] struct {
	ID           mysql.WhereMod[Q, int32]
	CourtGroupID mysql.WhereMod[Q, int32]
	ValidFrom    mysql.WhereMod[Q, time.Time]
	ValidTo      mysql.WhereMod[Q, time.Time]
}

func (pricePeriodWhere[Q]) AliasedAs(alias string) pricePeriodWhere[Q] {
	return buildPricePeriodWhere[Q](buildPricePeriodColumns(alias))
}

func buildPricePeriodWhere[Q mysql.Filterable](cols pricePeriodColumns) pricePeriodWhere[Q] {
	return pricePeriodWhere[Q]{
		ID:           mysql.Where[Q, int32](cols.ID),
		CourtGroupID: mysql.Where[Q, int32](cols.CourtGroupID),
		ValidFrom:    mysql.Where[Q, time.Time](cols.ValidFrom),
		ValidTo:      mysql.Where[Q, time.Time](cols.ValidTo),
	}
}

var PricePeriodErrors = &pricePeriodErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type pricePeriodErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// PricePeriodSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PricePeriodSetter struct {
	ID           omit.Val[int32]     `db:"id,pk,autoincr" `
	CourtGroupID omit.Val[int32]     `db:"court_group_id" `
	ValidFrom    omit.Val[time.Time] `db:"valid_from" `
	ValidTo      omit.Val[time.Time] `db:"valid_to" `
}

func (s PricePeriodSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.CourtGroupID.IsUnset() {
		vals = append(vals, "court_group_id")
	}

	if !s.ValidFrom.IsUnset() {
		vals = append(vals, "valid_from")
	}

	if !s.ValidTo.IsUnset() {
		vals = append(vals, "valid_to")
	}

	return vals
}

func (s PricePeriodSetter) Overwrite(t *PricePeriod) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.CourtGroupID.IsUnset() {
		t.CourtGroupID, _ = s.CourtGroupID.Get()
	}
	if !s.ValidFrom.IsUnset() {
		t.ValidFrom, _ = s.ValidFrom.Get()
	}
	if !s.ValidTo.IsUnset() {
		t.ValidTo, _ = s.ValidTo.Get()
	}
}

func (s *PricePeriodSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PricePeriods.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.ID)
		}

		if s.CourtGroupID.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.CourtGroupID)
		}

		if s.ValidFrom.IsUnset() {
			vals[2] = mysql.Raw("DEFAULT")
		} else {
			vals[2] = mysql.Arg(s.ValidFrom)
		}

		if s.ValidTo.IsUnset() {
			vals[3] = mysql.Raw("DEFAULT")
		} else {
			vals[3] = mysql.Arg(s.ValidTo)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PricePeriodSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("price_periods")...)
}

func (s PricePeriodSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if !s.CourtGroupID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "court_group_id")...),
			mysql.Arg(s.CourtGroupID),
		}})
	}

	if !s.ValidFrom.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "valid_from")...),
			mysql.Arg(s.ValidFrom),
		}})
	}

	if !s.ValidTo.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "valid_to")...),
			mysql.Arg(s.ValidTo),
		}})
	}

	return exprs
}

// FindPricePeriod retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPricePeriod(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*PricePeriod, error) {
	if len(cols) == 0 {
		return PricePeriods.Query(
			SelectWhere.PricePeriods.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return PricePeriods.Query(
		SelectWhere.PricePeriods.ID.EQ(IDPK),
		sm.Columns(PricePeriods.Columns().Only(cols...)),
	).One(ctx, exec)
}

// PricePeriodExists checks the presence of a single record by primary key
func PricePeriodExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return PricePeriods.Query(
		SelectWhere.PricePeriods.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PricePeriod is retrieved from the database
func (o *PricePeriod) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PricePeriods.AfterSelectHooks.RunHooks(ctx, exec, PricePeriodSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PricePeriods.AfterInsertHooks.RunHooks(ctx, exec, PricePeriodSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PricePeriods.AfterUpdateHooks.RunHooks(ctx, exec, PricePeriodSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PricePeriods.AfterDeleteHooks.RunHooks(ctx, exec, PricePeriodSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the PricePeriod
func (o *PricePeriod) PrimaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *PricePeriod) pkEQ() dialect.Expression {
	return mysql.Quote("price_periods", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PricePeriod
func (o *PricePeriod) Update(ctx context.Context, exec bob.Executor, s *PricePeriodSetter) error {
	_, err := PricePeriods.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single PricePeriod record with an executor
func (o *PricePeriod) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PricePeriods.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PricePeriod using the executor
func (o *PricePeriod) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PricePeriods.Query(
		SelectWhere.PricePeriods.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PricePeriodSlice is retrieved from the database
func (o PricePeriodSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PricePeriods.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PricePeriods.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PricePeriods.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PricePeriods.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PricePeriodSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("price_periods", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PricePeriodSlice) copyMatchingRows(from ...*PricePeriod) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PricePeriodSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PricePeriods.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PricePeriod:
				o.copyMatchingRows(retrieved)
			case []*PricePeriod:
				o.copyMatchingRows(retrieved...)
			case PricePeriodSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PricePeriod or a slice of PricePeriod
				// then run the AfterUpdateHooks on the slice
				_, err = PricePeriods.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PricePeriodSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PricePeriods.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PricePeriod:
				o.copyMatchingRows(retrieved)
			case []*PricePeriod:
				o.copyMatchingRows(retrieved...)
			case PricePeriodSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PricePeriod or a slice of PricePeriod
				// then run the AfterDeleteHooks on the slice
				_, err = PricePeriods.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PricePeriodSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PricePeriodSetter) error {
	_, err := PricePeriods.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o PricePeriodSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PricePeriods.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PricePeriodSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PricePeriods.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type pricePeriodJoins[Q dialect.Joinable] struct {
	typ        string
	CourtGroup func(context.Context) modAs[Q, courtGroupColumns]
	PriceRules func(context.Context) modAs[Q, priceRuleColumns]
}

func (j pricePeriodJoins[Q]) aliasedAs(alias string) pricePeriodJoins[Q] {
	return buildPricePeriodJoins[Q](buildPricePeriodColumns(alias), j.typ)
}

func buildPricePeriodJoins[Q dialect.Joinable](cols pricePeriodColumns, typ string) pricePeriodJoins[Q] {
	return pricePeriodJoins[Q]{
		typ:        typ,
		CourtGroup: pricePeriodsJoinCourtGroup[Q](cols, typ),
		PriceRules: pricePeriodsJoinPriceRules[Q](cols, typ),
	}
}

func pricePeriodsJoinCourtGroup[Q dialect.Joinable](from pricePeriodColumns, typ string) func(context.Context) modAs[Q, courtGroupColumns] {
	return func(ctx context.Context) modAs[Q, courtGroupColumns] {
		return modAs[Q, courtGroupColumns]{
			c: CourtGroupColumns,
			f: func(to courtGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, CourtGroups.Name().As(to.Alias())).On(
						to.ID.EQ(from.CourtGroupID),
					))
				}

				return mods
			},
		}
	}
}

func pricePeriodsJoinPriceRules[Q dialect.Joinable](from pricePeriodColumns, typ string) func(context.Context) modAs[Q, priceRuleColumns] {
	return func(ctx context.Context) modAs[Q, priceRuleColumns] {
		return modAs[Q, priceRuleColumns]{
			c: PriceRuleColumns,
			f: func(to priceRuleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PriceRules.Name().As(to.Alias())).On(
						to.PricePeriodID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

// CourtGroup starts a query for related objects on court_groups
func (o *PricePeriod) CourtGroup(mods ...bob.Mod[*dialect.SelectQuery]) CourtGroupsQuery {
	return CourtGroups.Query(append(mods,
		sm.Where(CourtGroupColumns.ID.EQ(mysql.Arg(o.CourtGroupID))),
	)...)
}

func (os PricePeriodSlice) CourtGroup(mods ...bob.Mod[*dialect.SelectQuery]) CourtGroupsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.CourtGroupID)
	}

	return CourtGroups.Query(append(mods,
		sm.Where(mysql.Group(CourtGroupColumns.ID).In(PKArgs...)),
	)...)
}

// PriceRules starts a query for related objects on price_rules
func (o *PricePeriod) PriceRules(mods ...bob.Mod[*dialect.SelectQuery]) PriceRulesQuery {
	return PriceRules.Query(append(mods,
		sm.Where(PriceRuleColumns.PricePeriodID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os PricePeriodSlice) PriceRules(mods ...bob.Mod[*dialect.SelectQuery]) PriceRulesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.ID)
	}

	return PriceRules.Query(append(mods,
		sm.Where(mysql.Group(PriceRuleColumns.PricePeriodID).In(PKArgs...)),
	)...)
}

func (o *PricePeriod) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "CourtGroup":
		rel, ok := retrieved.(*CourtGroup)
		if !ok {
			return fmt.Errorf("pricePeriod cannot load %T as %q", retrieved, name)
		}

		o.R.CourtGroup = rel

		if rel != nil {
			rel.R.PricePeriods = PricePeriodSlice{o}
		}
		return nil
	case "PriceRules":
		rels, ok := retrieved.(PriceRuleSlice)
		if !ok {
			return fmt.Errorf("pricePeriod cannot load %T as %q", retrieved, name)
		}

		o.R.PriceRules = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.PricePeriod = o
			}
		}
		return nil
	default:
		return fmt.Errorf("pricePeriod has no relationship %q", name)
	}
}

func PreloadPricePeriodCourtGroup(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*CourtGroup, CourtGroupSlice](orm.Relationship{
		Name: "CourtGroup",
		Sides: []orm.RelSide{
			{
				From: TableNames.PricePeriods,
				To:   TableNames.CourtGroups,
				FromColumns: []string{
					ColumnNames.PricePeriods.CourtGroupID,
				},
				ToColumns: []string{
					ColumnNames.CourtGroups.ID,
				},
			},
		},
	}, CourtGroups.Columns().Names(), opts...)
}

func ThenLoadPricePeriodCourtGroup(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPricePeriodCourtGroup(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PricePeriodCourtGroup", retrieved)
		}

		err := loader.LoadPricePeriodCourtGroup(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPricePeriodCourtGroup loads the pricePeriod's CourtGroup into the .R struct
func (o *PricePeriod) LoadPricePeriodCourtGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.CourtGroup = nil

	related, err := o.CourtGroup(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PricePeriods = PricePeriodSlice{o}

	o.R.CourtGroup = related
	return nil
}

// LoadPricePeriodCourtGroup loads the pricePeriod's CourtGroup into the .R struct
func (os PricePeriodSlice) LoadPricePeriodCourtGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	courtGroups, err := os.CourtGroup(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range courtGroups {
			if o.CourtGroupID != rel.ID {
				continue
			}

			rel.R.PricePeriods = append(rel.R.PricePeriods, o)

			o.R.CourtGroup = rel
			break
		}
	}

	return nil
}

func ThenLoadPricePeriodPriceRules(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPricePeriodPriceRules(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PricePeriodPriceRules", retrieved)
		}

		err := loader.LoadPricePeriodPriceRules(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPricePeriodPriceRules loads the pricePeriod's PriceRules into the .R struct
func (o *PricePeriod) LoadPricePeriodPriceRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PriceRules = nil

	related, err := o.PriceRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PricePeriod = o
	}

	o.R.PriceRules = related
	return nil
}

// LoadPricePeriodPriceRules loads the pricePeriod's PriceRules into the .R struct
func (os PricePeriodSlice) LoadPricePeriodPriceRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	priceRules, err := os.PriceRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.PriceRules = nil
	}

	for _, o := range os {
		for _, rel := range priceRules {
			if o.ID != rel.PricePeriodID {
				continue
			}

			rel.R.PricePeriod = o

			o.R.PriceRules = append(o.R.PriceRules, rel)
		}
	}

	return nil
}

func attachPricePeriodCourtGroup0(ctx context.Context, exec bob.Executor, count int, pricePeriod0 *PricePeriod, courtGroup1 *CourtGroup) (*PricePeriod, error) {
	setter := &PricePeriodSetter{
		CourtGroupID: omit.From(courtGroup1.ID),
	}

	err := pricePeriod0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPricePeriodCourtGroup0: %w", err)
	}

	return pricePeriod0, nil
}

func (pricePeriod0 *PricePeriod) InsertCourtGroup(ctx context.Context, exec bob.Executor, related *CourtGroupSetter) error {
	courtGroup1, err := CourtGroups.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPricePeriodCourtGroup0(ctx, exec, 1, pricePeriod0, courtGroup1)
	if err != nil {
		return err
	}

	pricePeriod0.R.CourtGroup = courtGroup1

	courtGroup1.R.PricePeriods = append(courtGroup1.R.PricePeriods, pricePeriod0)

	return nil
}

func (pricePeriod0 *PricePeriod) AttachCourtGroup(ctx context.Context, exec bob.Executor, courtGroup1 *CourtGroup) error {
	var err error

	_, err = attachPricePeriodCourtGroup0(ctx, exec, 1, pricePeriod0, courtGroup1)
	if err != nil {
		return err
	}

	pricePeriod0.R.CourtGroup = courtGroup1

	courtGroup1.R.PricePeriods = append(courtGroup1.R.PricePeriods, pricePeriod0)

	return nil
}

func insertPricePeriodPriceRules0(ctx context.Context, exec bob.Executor, priceRules1 []*PriceRuleSetter, pricePeriod0 *PricePeriod) (PriceRuleSlice, error) {
	for i := range priceRules1 {
		priceRules1[i].PricePeriodID = omit.From(pricePeriod0.ID)
	}

	ret, err := PriceRules.Insert(bob.ToMods(priceRules1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPricePeriodPriceRules0: %w", err)
	}

	return ret, nil
}

func attachPricePeriodPriceRules0(ctx context.Context, exec bob.Executor, count int, priceRules1 PriceRuleSlice, pricePeriod0 *PricePeriod) (PriceRuleSlice, error) {
	setter := &PriceRuleSetter{
		PricePeriodID: omit.From(pricePeriod0.ID),
	}

	err := priceRules1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPricePeriodPriceRules0: %w", err)
	}

	return priceRules1, nil
}

func (pricePeriod0 *PricePeriod) InsertPriceRules(ctx context.Context, exec bob.Executor, related ...*PriceRuleSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	priceRules1, err := insertPricePeriodPriceRules0(ctx, exec, related, pricePeriod0)
	if err != nil {
		return err
	}

	pricePeriod0.R.PriceRules = append(pricePeriod0.R.PriceRules, priceRules1...)

	for _, rel := range priceRules1 {
		rel.R.PricePeriod = pricePeriod0
	}
	return nil
}

func (pricePeriod0 *PricePeriod) AttachPriceRules(ctx context.Context, exec bob.Executor, related ...*PriceRule) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	priceRules1 := PriceRuleSlice(related)

	_, err = attachPricePeriodPriceRules0(ctx, exec, len(related), priceRules1, pricePeriod0)
	if err != nil {
		return err
	}

	pricePeriod0.R.PriceRules = append(pricePeriod0.R.PriceRules, priceRules1...)

	for _, rel := range related {
		rel.R.PricePeriod = pricePeriod0
	}

	return nil
}
