// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// PriceRule is an object representing the database table.
type PriceRule struct {
	ID            int32 `db:"id,pk,autoincr" `
	PricePeriodID int32 `db:"price_period_id" `
	// e.g., "*" (everyday except those specified), "st" (Saturday), "su" (Sunday), "hl" (Holiday), "!" (everyday force)
	DayPattern string          `db:"day_pattern" `
	TimeStart  string          `db:"time_start" `
	TimeEnd    string          `db:"time_end" `
	Price      decimal.Decimal `db:"price" `

	R priceRuleR `db:"-" `
}

// PriceRuleSlice is an alias for a slice of pointers to PriceRule.
// This should almost always be used instead of []*PriceRule.
type PriceRuleSlice []*PriceRule

// PriceRules contains methods to work with the price_rules table
var PriceRules = mysql.NewTablex[*PriceRule, PriceRuleSlice, *PriceRuleSetter]("price_rules", []string{"id"})

// PriceRulesQuery is a query on the price_rules table
type PriceRulesQuery = *mysql.ViewQuery[*PriceRule, PriceRuleSlice]

// priceRuleR is where relationships are stored.
type priceRuleR struct {
	PricePeriod *PricePeriod // price_rules_ibfk_1
}

type priceRuleColumnNames struct {
	ID            string
	PricePeriodID string
	DayPattern    string
	TimeStart     string
	TimeEnd       string
	Price         string
}

var PriceRuleColumns = buildPriceRuleColumns("price_rules")

type priceRuleColumns struct {
	tableAlias    string
	ID            mysql.Expression
	PricePeriodID mysql.Expression
	DayPattern    mysql.Expression
	TimeStart     mysql.Expression
	TimeEnd       mysql.Expression
	Price         mysql.Expression
}

func (c priceRuleColumns) Alias() string {
	return c.tableAlias
}

func (priceRuleColumns) AliasedAs(alias string) priceRuleColumns {
	return buildPriceRuleColumns(alias)
}

func buildPriceRuleColumns(alias string) priceRuleColumns {
	return priceRuleColumns{
		tableAlias:    alias,
		ID:            mysql.Quote(alias, "id"),
		PricePeriodID: mysql.Quote(alias, "price_period_id"),
		DayPattern:    mysql.Quote(alias, "day_pattern"),
		TimeStart:     mysql.Quote(alias, "time_start"),
		TimeEnd:       mysql.Quote(alias, "time_end"),
		Price:         mysql.Quote(alias, "price"),
	}
}

type priceRuleWhere[Q mysql.Filterable] struct {
	ID            mysql.WhereMod[Q, int32]
	PricePeriodID mysql.WhereMod[Q, int32]
	DayPattern    mysql.WhereMod[Q, string]
	TimeStart     mysql.WhereMod[Q, string]
	TimeEnd       mysql.WhereMod[Q, string]
	Price         mysql.WhereMod[Q, decimal.Decimal]
}

func (priceRuleWhere[Q]) AliasedAs(alias string) priceRuleWhere[Q] {
	return buildPriceRuleWhere[Q](buildPriceRuleColumns(alias))
}

func buildPriceRuleWhere[Q mysql.Filterable](cols priceRuleColumns) priceRuleWhere[Q] {
	return priceRuleWhere[Q]{
		ID:            mysql.Where[Q, int32](cols.ID),
		PricePeriodID: mysql.Where[Q, int32](cols.PricePeriodID),
		DayPattern:    mysql.Where[Q, string](cols.DayPattern),
		TimeStart:     mysql.Where[Q, string](cols.TimeStart),
		TimeEnd:       mysql.Where[Q, string](cols.TimeEnd),
		Price:         mysql.Where[Q, decimal.Decimal](cols.Price),
	}
}

var PriceRuleErrors = &priceRuleErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type priceRuleErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// PriceRuleSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PriceRuleSetter struct {
	ID            omit.Val[int32]           `db:"id,pk,autoincr" `
	PricePeriodID omit.Val[int32]           `db:"price_period_id" `
	DayPattern    omit.Val[string]          `db:"day_pattern" `
	TimeStart     omit.Val[string]          `db:"time_start" `
	TimeEnd       omit.Val[string]          `db:"time_end" `
	Price         omit.Val[decimal.Decimal] `db:"price" `
}

func (s PriceRuleSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.PricePeriodID.IsUnset() {
		vals = append(vals, "price_period_id")
	}

	if !s.DayPattern.IsUnset() {
		vals = append(vals, "day_pattern")
	}

	if !s.TimeStart.IsUnset() {
		vals = append(vals, "time_start")
	}

	if !s.TimeEnd.IsUnset() {
		vals = append(vals, "time_end")
	}

	if !s.Price.IsUnset() {
		vals = append(vals, "price")
	}

	return vals
}

func (s PriceRuleSetter) Overwrite(t *PriceRule) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.PricePeriodID.IsUnset() {
		t.PricePeriodID, _ = s.PricePeriodID.Get()
	}
	if !s.DayPattern.IsUnset() {
		t.DayPattern, _ = s.DayPattern.Get()
	}
	if !s.TimeStart.IsUnset() {
		t.TimeStart, _ = s.TimeStart.Get()
	}
	if !s.TimeEnd.IsUnset() {
		t.TimeEnd, _ = s.TimeEnd.Get()
	}
	if !s.Price.IsUnset() {
		t.Price, _ = s.Price.Get()
	}
}

func (s *PriceRuleSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PriceRules.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.ID)
		}

		if s.PricePeriodID.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.PricePeriodID)
		}

		if s.DayPattern.IsUnset() {
			vals[2] = mysql.Raw("DEFAULT")
		} else {
			vals[2] = mysql.Arg(s.DayPattern)
		}

		if s.TimeStart.IsUnset() {
			vals[3] = mysql.Raw("DEFAULT")
		} else {
			vals[3] = mysql.Arg(s.TimeStart)
		}

		if s.TimeEnd.IsUnset() {
			vals[4] = mysql.Raw("DEFAULT")
		} else {
			vals[4] = mysql.Arg(s.TimeEnd)
		}

		if s.Price.IsUnset() {
			vals[5] = mysql.Raw("DEFAULT")
		} else {
			vals[5] = mysql.Arg(s.Price)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PriceRuleSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("price_rules")...)
}

func (s PriceRuleSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if !s.PricePeriodID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "price_period_id")...),
			mysql.Arg(s.PricePeriodID),
		}})
	}

	if !s.DayPattern.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "day_pattern")...),
			mysql.Arg(s.DayPattern),
		}})
	}

	if !s.TimeStart.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "time_start")...),
			mysql.Arg(s.TimeStart),
		}})
	}

	if !s.TimeEnd.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "time_end")...),
			mysql.Arg(s.TimeEnd),
		}})
	}

	if !s.Price.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "price")...),
			mysql.Arg(s.Price),
		}})
	}

	return exprs
}

// FindPriceRule retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPriceRule(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*PriceRule, error) {
	if len(cols) == 0 {
		return PriceRules.Query(
			SelectWhere.PriceRules.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return PriceRules.Query(
		SelectWhere.PriceRules.ID.EQ(IDPK),
		sm.Columns(PriceRules.Columns().Only(cols...)),
	).One(ctx, exec)
}

// PriceRuleExists checks the presence of a single record by primary key
func PriceRuleExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return PriceRules.Query(
		SelectWhere.PriceRules.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PriceRule is retrieved from the database
func (o *PriceRule) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PriceRules.AfterSelectHooks.RunHooks(ctx, exec, PriceRuleSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PriceRules.AfterInsertHooks.RunHooks(ctx, exec, PriceRuleSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PriceRules.AfterUpdateHooks.RunHooks(ctx, exec, PriceRuleSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PriceRules.AfterDeleteHooks.RunHooks(ctx, exec, PriceRuleSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the PriceRule
func (o *PriceRule) PrimaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *PriceRule) pkEQ() dialect.Expression {
	return mysql.Quote("price_rules", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PriceRule
func (o *PriceRule) Update(ctx context.Context, exec bob.Executor, s *PriceRuleSetter) error {
	_, err := PriceRules.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single PriceRule record with an executor
func (o *PriceRule) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PriceRules.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PriceRule using the executor
func (o *PriceRule) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PriceRules.Query(
		SelectWhere.PriceRules.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PriceRuleSlice is retrieved from the database
func (o PriceRuleSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PriceRules.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PriceRules.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PriceRules.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PriceRules.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PriceRuleSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("price_rules", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PriceRuleSlice) copyMatchingRows(from ...*PriceRule) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PriceRuleSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PriceRules.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PriceRule:
				o.copyMatchingRows(retrieved)
			case []*PriceRule:
				o.copyMatchingRows(retrieved...)
			case PriceRuleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PriceRule or a slice of PriceRule
				// then run the AfterUpdateHooks on the slice
				_, err = PriceRules.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PriceRuleSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PriceRules.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PriceRule:
				o.copyMatchingRows(retrieved)
			case []*PriceRule:
				o.copyMatchingRows(retrieved...)
			case PriceRuleSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PriceRule or a slice of PriceRule
				// then run the AfterDeleteHooks on the slice
				_, err = PriceRules.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PriceRuleSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PriceRuleSetter) error {
	_, err := PriceRules.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o PriceRuleSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PriceRules.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PriceRuleSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PriceRules.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type priceRuleJoins[Q dialect.Joinable] struct {
	typ         string
	PricePeriod func(context.Context) modAs[Q, pricePeriodColumns]
}

func (j priceRuleJoins[Q]) aliasedAs(alias string) priceRuleJoins[Q] {
	return buildPriceRuleJoins[Q](buildPriceRuleColumns(alias), j.typ)
}

func buildPriceRuleJoins[Q dialect.Joinable](cols priceRuleColumns, typ string) priceRuleJoins[Q] {
	return priceRuleJoins[Q]{
		typ:         typ,
		PricePeriod: priceRulesJoinPricePeriod[Q](cols, typ),
	}
}

func priceRulesJoinPricePeriod[Q dialect.Joinable](from priceRuleColumns, typ string) func(context.Context) modAs[Q, pricePeriodColumns] {
	return func(ctx context.Context) modAs[Q, pricePeriodColumns] {
		return modAs[Q, pricePeriodColumns]{
			c: PricePeriodColumns,
			f: func(to pricePeriodColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PricePeriods.Name().As(to.Alias())).On(
						to.ID.EQ(from.PricePeriodID),
					))
				}

				return mods
			},
		}
	}
}

// PricePeriod starts a query for related objects on price_periods
func (o *PriceRule) PricePeriod(mods ...bob.Mod[*dialect.SelectQuery]) PricePeriodsQuery {
	return PricePeriods.Query(append(mods,
		sm.Where(PricePeriodColumns.ID.EQ(mysql.Arg(o.PricePeriodID))),
	)...)
}

func (os PriceRuleSlice) PricePeriod(mods ...bob.Mod[*dialect.SelectQuery]) PricePeriodsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.PricePeriodID)
	}

	return PricePeriods.Query(append(mods,
		sm.Where(mysql.Group(PricePeriodColumns.ID).In(PKArgs...)),
	)...)
}

func (o *PriceRule) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PricePeriod":
		rel, ok := retrieved.(*PricePeriod)
		if !ok {
			return fmt.Errorf("priceRule cannot load %T as %q", retrieved, name)
		}

		o.R.PricePeriod = rel

		if rel != nil {
			rel.R.PriceRules = PriceRuleSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("priceRule has no relationship %q", name)
	}
}

func PreloadPriceRulePricePeriod(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*PricePeriod, PricePeriodSlice](orm.Relationship{
		Name: "PricePeriod",
		Sides: []orm.RelSide{
			{
				From: TableNames.PriceRules,
				To:   TableNames.PricePeriods,
				FromColumns: []string{
					ColumnNames.PriceRules.PricePeriodID,
				},
				ToColumns: []string{
					ColumnNames.PricePeriods.ID,
				},
			},
		},
	}, PricePeriods.Columns().Names(), opts...)
}

func ThenLoadPriceRulePricePeriod(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadPriceRulePricePeriod(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load PriceRulePricePeriod", retrieved)
		}

		err := loader.LoadPriceRulePricePeriod(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadPriceRulePricePeriod loads the priceRule's PricePeriod into the .R struct
func (o *PriceRule) LoadPriceRulePricePeriod(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PricePeriod = nil

	related, err := o.PricePeriod(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PriceRules = PriceRuleSlice{o}

	o.R.PricePeriod = related
	return nil
}

// LoadPriceRulePricePeriod loads the priceRule's PricePeriod into the .R struct
func (os PriceRuleSlice) LoadPriceRulePricePeriod(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	pricePeriods, err := os.PricePeriod(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range pricePeriods {
			if o.PricePeriodID != rel.ID {
				continue
			}

			rel.R.PriceRules = append(rel.R.PriceRules, o)

			o.R.PricePeriod = rel
			break
		}
	}

	return nil
}

func attachPriceRulePricePeriod0(ctx context.Context, exec bob.Executor, count int, priceRule0 *PriceRule, pricePeriod1 *PricePeriod) (*PriceRule, error) {
	setter := &PriceRuleSetter{
		PricePeriodID: omit.From(pricePeriod1.ID),
	}

	err := priceRule0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPriceRulePricePeriod0: %w", err)
	}

	return priceRule0, nil
}

func (priceRule0 *PriceRule) InsertPricePeriod(ctx context.Context, exec bob.Executor, related *PricePeriodSetter) error {
	pricePeriod1, err := PricePeriods.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPriceRulePricePeriod0(ctx, exec, 1, priceRule0, pricePeriod1)
	if err != nil {
		return err
	}

	priceRule0.R.PricePeriod = pricePeriod1

	pricePeriod1.R.PriceRules = append(pricePeriod1.R.PriceRules, priceRule0)

	return nil
}

func (priceRule0 *PriceRule) AttachPricePeriod(ctx context.Context, exec bob.Executor, pricePeriod1 *PricePeriod) error {
	var err error

	_, err = attachPriceRulePricePeriod0(ctx, exec, 1, priceRule0, pricePeriod1)
	if err != nil {
		return err
	}

	priceRule0.R.PricePeriod = pricePeriod1

	pricePeriod1.R.PriceRules = append(pricePeriod1.R.PriceRules, priceRule0)

	return nil
}
