// Code generated by BobGen mysql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// User is an object representing the database table.
type User struct {
	UID         string              `db:"uid,pk" `
	PhoneNumber string              `db:"phone_number" `
	Country     string              `db:"country" `
	ExternalID  null.Val[string]    `db:"external_id" `
	CreatedAt   null.Val[time.Time] `db:"created_at" `
	UpdatedAt   null.Val[time.Time] `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the users table
var Users = mysql.NewTablex[*User, UserSlice, *UserSetter]("users", []string{"uid"})

// UsersQuery is a query on the users table
type UsersQuery = *mysql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	UIDUserPref *UserPref // user_pref_ibfk_1
}

type userColumnNames struct {
	UID         string
	PhoneNumber string
	Country     string
	ExternalID  string
	CreatedAt   string
	UpdatedAt   string
}

var UserColumns = buildUserColumns("users")

type userColumns struct {
	tableAlias  string
	UID         mysql.Expression
	PhoneNumber mysql.Expression
	Country     mysql.Expression
	ExternalID  mysql.Expression
	CreatedAt   mysql.Expression
	UpdatedAt   mysql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		tableAlias:  alias,
		UID:         mysql.Quote(alias, "uid"),
		PhoneNumber: mysql.Quote(alias, "phone_number"),
		Country:     mysql.Quote(alias, "country"),
		ExternalID:  mysql.Quote(alias, "external_id"),
		CreatedAt:   mysql.Quote(alias, "created_at"),
		UpdatedAt:   mysql.Quote(alias, "updated_at"),
	}
}

type userWhere[Q mysql.Filterable] struct {
	UID         mysql.WhereMod[Q, string]
	PhoneNumber mysql.WhereMod[Q, string]
	Country     mysql.WhereMod[Q, string]
	ExternalID  mysql.WhereNullMod[Q, string]
	CreatedAt   mysql.WhereNullMod[Q, time.Time]
	UpdatedAt   mysql.WhereNullMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q mysql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		UID:         mysql.Where[Q, string](cols.UID),
		PhoneNumber: mysql.Where[Q, string](cols.PhoneNumber),
		Country:     mysql.Where[Q, string](cols.Country),
		ExternalID:  mysql.WhereNull[Q, string](cols.ExternalID),
		CreatedAt:   mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

var UserErrors = &userErrors{
	ErrUniquePrimary: &UniqueConstraintError{s: "PRIMARY"},
}

type userErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	UID         omit.Val[string]        `db:"uid,pk" `
	PhoneNumber omit.Val[string]        `db:"phone_number" `
	Country     omit.Val[string]        `db:"country" `
	ExternalID  omitnull.Val[string]    `db:"external_id" `
	CreatedAt   omitnull.Val[time.Time] `db:"created_at" `
	UpdatedAt   omitnull.Val[time.Time] `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.UID.IsUnset() {
		vals = append(vals, "uid")
	}

	if !s.PhoneNumber.IsUnset() {
		vals = append(vals, "phone_number")
	}

	if !s.Country.IsUnset() {
		vals = append(vals, "country")
	}

	if !s.ExternalID.IsUnset() {
		vals = append(vals, "external_id")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if !s.UID.IsUnset() {
		t.UID, _ = s.UID.Get()
	}
	if !s.PhoneNumber.IsUnset() {
		t.PhoneNumber, _ = s.PhoneNumber.Get()
	}
	if !s.Country.IsUnset() {
		t.Country, _ = s.Country.Get()
	}
	if !s.ExternalID.IsUnset() {
		t.ExternalID, _ = s.ExternalID.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.GetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.GetNull()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.UID.IsUnset() {
			vals[0] = mysql.Raw("DEFAULT")
		} else {
			vals[0] = mysql.Arg(s.UID)
		}

		if s.PhoneNumber.IsUnset() {
			vals[1] = mysql.Raw("DEFAULT")
		} else {
			vals[1] = mysql.Arg(s.PhoneNumber)
		}

		if s.Country.IsUnset() {
			vals[2] = mysql.Raw("DEFAULT")
		} else {
			vals[2] = mysql.Arg(s.Country)
		}

		if s.ExternalID.IsUnset() {
			vals[3] = mysql.Raw("DEFAULT")
		} else {
			vals[3] = mysql.Arg(s.ExternalID)
		}

		if s.CreatedAt.IsUnset() {
			vals[4] = mysql.Raw("DEFAULT")
		} else {
			vals[4] = mysql.Arg(s.CreatedAt)
		}

		if s.UpdatedAt.IsUnset() {
			vals[5] = mysql.Raw("DEFAULT")
		} else {
			vals[5] = mysql.Arg(s.UpdatedAt)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("users")...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.UID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "uid")...),
			mysql.Arg(s.UID),
		}})
	}

	if !s.PhoneNumber.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "phone_number")...),
			mysql.Arg(s.PhoneNumber),
		}})
	}

	if !s.Country.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "country")...),
			mysql.Arg(s.Country),
		}})
	}

	if !s.ExternalID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "external_id")...),
			mysql.Arg(s.ExternalID),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, UIDPK string, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			SelectWhere.Users.UID.EQ(UIDPK),
		).One(ctx, exec)
	}

	return Users.Query(
		SelectWhere.Users.UID.EQ(UIDPK),
		sm.Columns(Users.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, UIDPK string) (bool, error) {
	return Users.Query(
		SelectWhere.Users.UID.EQ(UIDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the User
func (o *User) PrimaryKeyVals() bob.Expression {
	return mysql.Arg(o.UID)
}

func (o *User) pkEQ() dialect.Expression {
	return mysql.Quote("users", "uid").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	_, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		SelectWhere.Users.UID.EQ(o.UID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("users", "uid").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.UID != old.UID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ         string
	UIDUserPref func(context.Context) modAs[Q, userPrefColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ:         typ,
		UIDUserPref: usersJoinUIDUserPref[Q](cols, typ),
	}
}

func usersJoinUIDUserPref[Q dialect.Joinable](from userColumns, typ string) func(context.Context) modAs[Q, userPrefColumns] {
	return func(ctx context.Context) modAs[Q, userPrefColumns] {
		return modAs[Q, userPrefColumns]{
			c: UserPrefColumns,
			f: func(to userPrefColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserPrefs.Name().As(to.Alias())).On(
						to.UID.EQ(from.UID),
					))
				}

				return mods
			},
		}
	}
}

// UIDUserPref starts a query for related objects on user_pref
func (o *User) UIDUserPref(mods ...bob.Mod[*dialect.SelectQuery]) UserPrefsQuery {
	return UserPrefs.Query(append(mods,
		sm.Where(UserPrefColumns.UID.EQ(mysql.Arg(o.UID))),
	)...)
}

func (os UserSlice) UIDUserPref(mods ...bob.Mod[*dialect.SelectQuery]) UserPrefsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = mysql.ArgGroup(o.UID)
	}

	return UserPrefs.Query(append(mods,
		sm.Where(mysql.Group(UserPrefColumns.UID).In(PKArgs...)),
	)...)
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "UIDUserPref":
		rel, ok := retrieved.(*UserPref)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UIDUserPref = rel

		if rel != nil {
			rel.R.UIDUser = o
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

func PreloadUserUIDUserPref(opts ...mysql.PreloadOption) mysql.Preloader {
	return mysql.Preload[*UserPref, UserPrefSlice](orm.Relationship{
		Name: "UIDUserPref",
		Sides: []orm.RelSide{
			{
				From: TableNames.Users,
				To:   TableNames.UserPrefs,
				FromColumns: []string{
					ColumnNames.Users.UID,
				},
				ToColumns: []string{
					ColumnNames.UserPrefs.UID,
				},
			},
		},
	}, UserPrefs.Columns().Names(), opts...)
}

func ThenLoadUserUIDUserPref(queryMods ...bob.Mod[*dialect.SelectQuery]) mysql.Loader {
	return mysql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserUIDUserPref(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserUIDUserPref", retrieved)
		}

		err := loader.LoadUserUIDUserPref(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserUIDUserPref loads the user's UIDUserPref into the .R struct
func (o *User) LoadUserUIDUserPref(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UIDUserPref = nil

	related, err := o.UIDUserPref(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UIDUser = o

	o.R.UIDUserPref = related
	return nil
}

// LoadUserUIDUserPref loads the user's UIDUserPref into the .R struct
func (os UserSlice) LoadUserUIDUserPref(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userPrefs, err := os.UIDUserPref(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range userPrefs {
			if o.UID != rel.UID {
				continue
			}

			rel.R.UIDUser = o

			o.R.UIDUserPref = rel
			break
		}
	}

	return nil
}

func insertUserUIDUserPref0(ctx context.Context, exec bob.Executor, userPref1 *UserPrefSetter, user0 *User) (*UserPref, error) {
	userPref1.UID = omit.From(user0.UID)

	ret, err := UserPrefs.Insert(userPref1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUIDUserPref0: %w", err)
	}

	return ret, nil
}

func attachUserUIDUserPref0(ctx context.Context, exec bob.Executor, count int, userPref1 *UserPref, user0 *User) (*UserPref, error) {
	setter := &UserPrefSetter{
		UID: omit.From(user0.UID),
	}

	err := userPref1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUIDUserPref0: %w", err)
	}

	return userPref1, nil
}

func (user0 *User) InsertUIDUserPref(ctx context.Context, exec bob.Executor, related *UserPrefSetter) error {
	userPref1, err := insertUserUIDUserPref0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UIDUserPref = userPref1

	userPref1.R.UIDUser = user0

	return nil
}

func (user0 *User) AttachUIDUserPref(ctx context.Context, exec bob.Executor, userPref1 *UserPref) error {
	var err error

	_, err = attachUserUIDUserPref0(ctx, exec, 1, userPref1, user0)
	if err != nil {
		return err
	}

	user0.R.UIDUserPref = userPref1

	userPref1.R.UIDUser = user0

	return nil
}
