// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/xtp-tour/xtp-tour/api/pkg/db"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type MockQueue
func (_mock *MockQueue) Enqueue(ctx context.Context, userId string, data db.NotificationQueueData) error {
	ret := _mock.Called(ctx, userId, data)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.NotificationQueueData) error); ok {
		r0 = returnFunc(ctx, userId, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - data db.NotificationQueueData
func (_e *MockQueue_Expecter) Enqueue(ctx interface{}, userId interface{}, data interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, userId, data)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, userId string, data db.NotificationQueueData)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.NotificationQueueData
		if args[2] != nil {
			arg2 = args[2].(db.NotificationQueueData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(err error) *MockQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, userId string, data db.NotificationQueueData) error) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetNext provides a mock function for the type MockQueue
func (_mock *MockQueue) GetNext(ctx context.Context) (*db.NotificationQueueRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNext")
	}

	var r0 *db.NotificationQueueRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*db.NotificationQueueRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *db.NotificationQueueRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.NotificationQueueRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_GetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNext'
type MockQueue_GetNext_Call struct {
	*mock.Call
}

// GetNext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueue_Expecter) GetNext(ctx interface{}) *MockQueue_GetNext_Call {
	return &MockQueue_GetNext_Call{Call: _e.mock.On("GetNext", ctx)}
}

func (_c *MockQueue_GetNext_Call) Run(run func(ctx context.Context)) *MockQueue_GetNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueue_GetNext_Call) Return(notificationQueueRow *db.NotificationQueueRow, err error) *MockQueue_GetNext_Call {
	_c.Call.Return(notificationQueueRow, err)
	return _c
}

func (_c *MockQueue_GetNext_Call) RunAndReturn(run func(ctx context.Context) (*db.NotificationQueueRow, error)) *MockQueue_GetNext_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementRetryCount provides a mock function for the type MockQueue
func (_mock *MockQueue) IncrementRetryCount(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetryCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_IncrementRetryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRetryCount'
type MockQueue_IncrementRetryCount_Call struct {
	*mock.Call
}

// IncrementRetryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQueue_Expecter) IncrementRetryCount(ctx interface{}, id interface{}) *MockQueue_IncrementRetryCount_Call {
	return &MockQueue_IncrementRetryCount_Call{Call: _e.mock.On("IncrementRetryCount", ctx, id)}
}

func (_c *MockQueue_IncrementRetryCount_Call) Run(run func(ctx context.Context, id string)) *MockQueue_IncrementRetryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_IncrementRetryCount_Call) Return(err error) *MockQueue_IncrementRetryCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_IncrementRetryCount_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockQueue_IncrementRetryCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCompleted provides a mock function for the type MockQueue
func (_mock *MockQueue) MarkCompleted(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_MarkCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCompleted'
type MockQueue_MarkCompleted_Call struct {
	*mock.Call
}

// MarkCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQueue_Expecter) MarkCompleted(ctx interface{}, id interface{}) *MockQueue_MarkCompleted_Call {
	return &MockQueue_MarkCompleted_Call{Call: _e.mock.On("MarkCompleted", ctx, id)}
}

func (_c *MockQueue_MarkCompleted_Call) Run(run func(ctx context.Context, id string)) *MockQueue_MarkCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_MarkCompleted_Call) Return(err error) *MockQueue_MarkCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_MarkCompleted_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockQueue_MarkCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockQueue
func (_mock *MockQueue) MarkFailed(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockQueue_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQueue_Expecter) MarkFailed(ctx interface{}, id interface{}) *MockQueue_MarkFailed_Call {
	return &MockQueue_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id)}
}

func (_c *MockQueue_MarkFailed_Call) Run(run func(ctx context.Context, id string)) *MockQueue_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_MarkFailed_Call) Return(err error) *MockQueue_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockQueue_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}
