// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSpecificSender creates a new instance of MockSpecificSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecificSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecificSender {
	mock := &MockSpecificSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSpecificSender is an autogenerated mock type for the SpecificSender type
type MockSpecificSender struct {
	mock.Mock
}

type MockSpecificSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecificSender) EXPECT() *MockSpecificSender_Expecter {
	return &MockSpecificSender_Expecter{mock: &_m.Mock}
}

// GetDeliveryMethod provides a mock function for the type MockSpecificSender
func (_mock *MockSpecificSender) GetDeliveryMethod() uint8 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeliveryMethod")
	}

	var r0 uint8
	if returnFunc, ok := ret.Get(0).(func() uint8); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint8)
	}
	return r0
}

// MockSpecificSender_GetDeliveryMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeliveryMethod'
type MockSpecificSender_GetDeliveryMethod_Call struct {
	*mock.Call
}

// GetDeliveryMethod is a helper method to define mock.On call
func (_e *MockSpecificSender_Expecter) GetDeliveryMethod() *MockSpecificSender_GetDeliveryMethod_Call {
	return &MockSpecificSender_GetDeliveryMethod_Call{Call: _e.mock.On("GetDeliveryMethod")}
}

func (_c *MockSpecificSender_GetDeliveryMethod_Call) Run(run func()) *MockSpecificSender_GetDeliveryMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSpecificSender_GetDeliveryMethod_Call) Return(v uint8) *MockSpecificSender_GetDeliveryMethod_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockSpecificSender_GetDeliveryMethod_Call) RunAndReturn(run func() uint8) *MockSpecificSender_GetDeliveryMethod_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSpecificSender
func (_mock *MockSpecificSender) Send(ctx context.Context, address string, topic string, message string) error {
	ret := _mock.Called(ctx, address, topic, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, address, topic, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSpecificSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSpecificSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - topic string
//   - message string
func (_e *MockSpecificSender_Expecter) Send(ctx interface{}, address interface{}, topic interface{}, message interface{}) *MockSpecificSender_Send_Call {
	return &MockSpecificSender_Send_Call{Call: _e.mock.On("Send", ctx, address, topic, message)}
}

func (_c *MockSpecificSender_Send_Call) Run(run func(ctx context.Context, address string, topic string, message string)) *MockSpecificSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSpecificSender_Send_Call) Return(err error) *MockSpecificSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSpecificSender_Send_Call) RunAndReturn(run func(ctx context.Context, address string, topic string, message string) error) *MockSpecificSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
