root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/api cmd/server/main.go"
bin = "./bin/api"
full_bin = "./bin/api"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "bin", ".git", ".data", ".tmp"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air.log"


[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 