services:
  app:
    build:
      context: ..
      dockerfile: api/Dockerfile.deploy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=xtp_tour
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xtp-tour 