name: Backend CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/backend.yaml'
  workflow_call:
  workflow_dispatch:

# Add permissions needed for GitHub Container Registry
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/${{ github.repository }}/api

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          check-latest: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: make build-arm

      - name: Test
        run: make test

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        if: github.event_name != 'pull_request'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push API Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Integration Tests Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Int.Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ github.sha }}-test
            ${{ env.REGISTRY }}:latest-test
          labels: ${{ steps.meta.outputs.labels }}